---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode
  namespace: external-dns
spec:
  encryptedData:
    LINODE_TOKEN: AgCEjm84k1BKDFXil+v0Fiam+9gMjXIH2c5rWmA/hwoFTQNiw9WL9IkioSWy26Fi3gHRJbxE7BP4NERa75B4UyHd+NWtQ5LUvedFloJ8yk136Nd9I5n6H97sV7VupoB6PkMVujsnXwcPmUJ46kmZU9f52d2d9VvODyes/7p8zGGeMJb1/lzo71eOWiF1qxT20Q+2cutXiy81trGeMgMcxuXK3wdLmTfQMs9zVbPPw65ByQ0pGjsY9fiy4McDjVDCAT0FhW6z1JmcAVDcgFOvazuW6lUtVMFp0DKbcxDjXsiOLM8hlrRe/7jwffg5yVkLqkD9uSXMjYXuO4/VAQ7xzuVdCArgvzk/+EdlGYiiH69Mb48YHxi5EvwupxlUQc48yrP6cv73I7Yfqz47jPITHzQrGYeG5fX4tuVhBlVRzQM7PKx9C+mnItHGKyda5Zv37VX5oNWew2Wl095SY7AqE4je0X4Sh3XcHSHrFtKiiXlJLK0Kwj6KyEh55ewMVJiq7nacR3Dr0VzRl0GhtOVkiOZ6hwU5vei6JrPTBFYZdi8YdrGoemWmre3V2iyn2KaZ41s2ECMQ01bznLdu3Q8aJqL6Ilg/JZFZoSQ2iB/bY/sBZVhV3H8gPzjx8QjxtFvvOkgKbYKhxE7xJA8HgqgRF3H3BmDo8fhAu5OENDPTevOd4a7QtX0nJXwKhf0riuNImO6FoyhTAq9S6Oa0fQIZtMy82HVDjTMX8aW3b8btc/bP1NEnsDpiAiV3hywO1yCJf7qHPhrUJG8pO/HpraADm3xw
  template:
    metadata:
      name: linode
      namespace: external-dns
