---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode
  namespace: external-dns
spec:
  encryptedData:
    LINODE_TOKEN: AgBsa0M1kOC85PIyagLh4gIwHxut/2UhGkY+F2MAVbHZJyBdhiyyTTGlmWci2PaqzvfV+/s1A/m7rk+xBOHeO46otrf1iQLA1HzcGdLCm+juEzAKlH3KVNfFUJaIemmBMoJuNiunbKr5Yuv+QxkdIPEUf/Sa5y9uzsXzNHlLiVJheCs2x56X6uPz+6cl0uf8kccCJYsBfi56JedkpUeX1Kky/WEqciSczf4UqQA92ndf3ZXTHlXqUI40MIV79cFiYqhOs15Yc+4R+xuWkBwKCU0BesGBnF9fqcO/f7QPk1uVBVi9rWG71EDYSF1+XZawPunYDz3l1ZwSYCfXLcIu1uKy+vGRiu57RcKq/h4O/172hvNBFxaVVJ0Uhm63Chf6YvQfWFQb68fJNDkHhsg+UomyajedXbl3l58Hrn9Jkr49AY2ZjTVkcddx2hg4h3Y6K1uzoMSeRPiJb0WBa/3xZ36JxwgBy4aKlzpZmuMndjJaaQB7zh25BjfT96cezDwh8EGvZ+ok7fDnJZMkds47F0r/+zOIgpACT3YLTOaIgiM+V0XXM6plf3D3ZWhepG12hwBVJhuPJMjAnK1nn63y5PfP7dNpd7ho1k0VB2jwvS22Ekwni901djAUBeJwO+J9hiDpxDfB6I+P7eawKhqstvi3hhlEh+XscBMgal/n8H+iSHcHgo/Hpn4Qx0s9M70ZSkGn4TB5T36FpLDW7MRsNrSoCYEq6x0udK2TCTzlHpEHiQK+T3PeCNJkSVXYql6ekR+ZC5PzQZYoWTr6dUzjIYZD
  template:
    metadata:
      name: linode
      namespace: external-dns
