apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  interval: 5m

  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system

  values:
    metrics:
      enabled: true

    serviceMonitor:
      enabled: false