apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets-controller
  interval: 5m

  chart:
    spec:
      chart: sealed-secrets
      version: 2.13.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system

  values:
    ingress:
      enabled: false

    metrics:
      serviceMonitor:
        enabled: true
      dashboards:
         create: false