apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-exporter
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    chart: kubernetes-event-exporter
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.10.0

    helm:
      releaseName: event-exporter

      valuesObject:
        config:
          logFormat: "json"
          logLevel: "warn"

        metrics:
          enabled: true

          serviceMonitor:
            enabled: true

          prometheusRule:
            enabled: true
