apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: apps
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: forecastle
  interval: 5m
  chart:
    spec:
      chart: ./deployments/kubernetes/chart/forecastle
      sourceRef:
        kind: GitRepository
        name: forecastle
        namespace: flux-system
      version: v1.0.69
  values:
    nameOverride: forecastle

    forecastle:
      createCustomResource: true

      labels: {}

      namespace: apps

      image:
        name: stakater/forecastle
        tag: SNAPSHOT-PR-174-b77f9800

      deployment:
        replicas: 1

      config:
        customApps: {}
        headerBackground: null
        headerForeground: null
        instanceName: null
        crdEnabled: true
        namespaceSelector:
          matchNames:
            - logging
            - monitoring
            - kubernetes-dashboard
            - apps
            - infra
            - kube-system
            - vault
        title: Launch Pad

      ingress:
        enabled: false
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: forecastle
#   namespace: apps
#   annotations:
#     kubernetes.io/tls-acme: "true"
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: launchpad.cluster.rebelinblue.com
#       http:
#         paths:
#           - path: /
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: forecastle
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#         - launchpad.cluster.rebelinblue.com
#       secretName: forecastle-tls
