---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: forecastleapps.forecastle.stakater.com
spec:
  conversion:
    strategy: None
  group: forecastle.stakater.com
  names:
    kind: ForecastleApp
    listKind: ForecastleAppList
    plural: forecastleapps
    singular: forecastleapp
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              group:
                type: string
              icon:
                type: string
              instance:
                type: string
              name:
                type: string
              networkRestricted:
                type: boolean
              properties:
                additionalProperties:
                  type: string
                type: object
              url:
                type: string
              urlFrom:
                properties:
                  ingressRef:
                    type: object
                  routeRef:
                    type: object
                type: object
            required:
            - name
            - group
            - icon
            type: object
          status:
            type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: apps
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: forecastle
  interval: 5m
  chart:
    spec:
      chart: forecastle
      sourceRef:
        kind: HelmRepository
        name: forecastle
        namespace: flux-system
      version: v1.0.69
  values:
    nameOverride: forecastle

    forecastle:
      createCustomResource: false

      labels: {}

      namespace: apps

      image:
        name: rebelinblue/forecastle
        tag: 1.0.58

      deployment:
        replicas: 1

      config:
        customApps: {}
        headerBackground: null
        headerForeground: null
        instanceName: null
        crdEnabled: true
        namespaceSelector:
          matchNames:
            - logging
            - media
            - monitoring
            - kubernetes-dashboard
            - apps
            - infra
            - kube-system
            - vault
        title: Launch Pad

      ingress:
        enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forecastle
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: launchpad.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: forecastle
                port:
                  number: 80
  tls:
    - hosts:
        - launchpad.cluster.rebelinblue.com
      secretName: forecastle-tls
