---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: letsencrypt@stephen.rebelinblue.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: traefik
            ingressTemplate:
              annotations:
                "kubernetes.io/ingress.class": "traefik"
                "traefik.ingress.kubernetes.io/frontend-entry-points": "http"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@stephen.rebelinblue.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
            ingressTemplate:
              annotations:
                "kubernetes.io/ingress.class": "traefik"
                "traefik.ingress.kubernetes.io/frontend-entry-points": "http"
