apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
  labels:
    app: debug
spec:
  selector:
    matchLabels:
      name: debug
  template:
    metadata:
      labels:
        name: debug
      annotations:
        linkerd.io/inject: disabled
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: utils
        image: rebelinblue/utils:0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: host
            mountPath: /host
      volumes:
        - name: host
          hostPath:
            path: /
  updateStrategy:
    type: RollingUpdate