apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: metrics-server
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 5.10.10
  values:
    image:
      repository: willdockerhub/metrics-server@sha256
      tag: 98d633a38661784fde52bcb9f7e616114c848e201a6b925a037a26be1b2e3ed5

    containerSecurityContext:
      enabled: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false

    command: /metrics-server

    extraArgs:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP

    service:
      labels:
        kubernetes.io/cluster-service: "true"
        kubernetes.io/name: "Metrics-Server"

    podAnnotations:
      scheduler.alpha.kubernetes.io/critical-pod: ''

    priorityClassName: system-node-critical
