apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plans.upgrade.cattle.io
spec:
  group: upgrade.cattle.io
  names:
    kind: Plan
    plural: plans
    singular: plan
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.upgrade.image
      name: Image
      type: string
    - jsonPath: .spec.channel
      name: Channel
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              channel:
                nullable: true
                type: string
              concurrency:
                type: integer
              cordon:
                type: boolean
              drain:
                nullable: true
                properties:
                  deleteLocalData:
                    nullable: true
                    type: boolean
                  disableEviction:
                    type: boolean
                  force:
                    type: boolean
                  gracePeriod:
                    nullable: true
                    type: integer
                  ignoreDaemonSets:
                    nullable: true
                    type: boolean
                  skipWaitForDeleteTimeout:
                    type: integer
                  timeout:
                    nullable: true
                    type: integer
                type: object
              nodeSelector:
                nullable: true
                properties:
                  matchExpressions:
                    items:
                      properties:
                        key:
                          nullable: true
                          type: string
                        operator:
                          nullable: true
                          type: string
                        values:
                          items:
                            nullable: true
                            type: string
                          nullable: true
                          type: array
                      type: object
                    nullable: true
                    type: array
                  matchLabels:
                    additionalProperties:
                      nullable: true
                      type: string
                    nullable: true
                    type: object
                type: object
              prepare:
                nullable: true
                properties:
                  args:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  command:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  envFrom:
                    items:
                      properties:
                        configMapRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                        prefix:
                          nullable: true
                          type: string
                        secretRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                      type: object
                    nullable: true
                    type: array
                  envs:
                    items:
                      properties:
                        name:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                        valueFrom:
                          nullable: true
                          properties:
                            configMapKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                            fieldRef:
                              nullable: true
                              properties:
                                apiVersion:
                                  nullable: true
                                  type: string
                                fieldPath:
                                  nullable: true
                                  type: string
                              type: object
                            resourceFieldRef:
                              nullable: true
                              properties:
                                containerName:
                                  nullable: true
                                  type: string
                                divisor:
                                  nullable: true
                                  type: string
                                resource:
                                  nullable: true
                                  type: string
                              type: object
                            secretKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                          type: object
                      type: object
                    nullable: true
                    type: array
                  image:
                    nullable: true
                    type: string
                type: object
              secrets:
                items:
                  properties:
                    name:
                      nullable: true
                      type: string
                    path:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              serviceAccountName:
                nullable: true
                type: string
              tolerations:
                items:
                  properties:
                    effect:
                      nullable: true
                      type: string
                    key:
                      nullable: true
                      type: string
                    operator:
                      nullable: true
                      type: string
                    tolerationSeconds:
                      nullable: true
                      type: integer
                    value:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              upgrade:
                nullable: true
                properties:
                  args:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  command:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  envFrom:
                    items:
                      properties:
                        configMapRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                        prefix:
                          nullable: true
                          type: string
                        secretRef:
                          nullable: true
                          properties:
                            name:
                              nullable: true
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                      type: object
                    nullable: true
                    type: array
                  envs:
                    items:
                      properties:
                        name:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                        valueFrom:
                          nullable: true
                          properties:
                            configMapKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                            fieldRef:
                              nullable: true
                              properties:
                                apiVersion:
                                  nullable: true
                                  type: string
                                fieldPath:
                                  nullable: true
                                  type: string
                              type: object
                            resourceFieldRef:
                              nullable: true
                              properties:
                                containerName:
                                  nullable: true
                                  type: string
                                divisor:
                                  nullable: true
                                  type: string
                                resource:
                                  nullable: true
                                  type: string
                              type: object
                            secretKeyRef:
                              nullable: true
                              properties:
                                key:
                                  nullable: true
                                  type: string
                                name:
                                  nullable: true
                                  type: string
                                optional:
                                  nullable: true
                                  type: boolean
                              type: object
                          type: object
                      type: object
                    nullable: true
                    type: array
                  image:
                    nullable: true
                    type: string
                type: object
              version:
                nullable: true
                type: string
            required:
            - upgrade
            type: object
          status:
            properties:
              applying:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      nullable: true
                      type: string
                    lastUpdateTime:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              latestHash:
                nullable: true
                type: string
              latestVersion:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-controller-env
  namespace: kube-system
data:
  SYSTEM_UPGRADE_CONTROLLER_DEBUG: "false"
  SYSTEM_UPGRADE_CONTROLLER_THREADS: "2"
  SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: "900"
  SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: "99"
  SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: "Always"
  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: "rancher/kubectl:v1.19.7"
  SYSTEM_UPGRADE_JOB_PRIVILEGED: "true"
  SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: "900"
  SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: "15m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      upgrade.cattle.io/controller: system-upgrade-controller
  template:
    metadata:
      labels:
        upgrade.cattle.io/controller: system-upgrade-controller # necessary to avoid drain
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: In
                values:
                - "true"
      serviceAccountName: system-upgrade
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: system-upgrade-controller
        image: rancher/system-upgrade-controller:v0.9.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: default-controller-env
        env:
        - name: SYSTEM_UPGRADE_CONTROLLER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['upgrade.cattle.io/controller']
        - name: SYSTEM_UPGRADE_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: etc-ssl
          mountPath: /etc/ssl
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: etc-ssl
        hostPath:
          path: /etc/ssl
          type: Directory
      - name: tmp
        emptyDir: {}
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: kube-system
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
    - { key: k3os.io/mode, operator: DoesNotExist }
    - { key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"] }
    - key: kubernetes.io/arch
      operator: In
      values:
      - "arm64"
  serviceAccountName: system-upgrade
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: kube-system
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/stable
  nodeSelector:
    matchExpressions:
      # - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: k3os.io/mode, operator: DoesNotExist}
      - {key: node-role.kubernetes.io/master, operator: NotIn, values: ["true"]}
      - {key: node-role.kubernetes.io/control-plane, operator: DoesNotExist}
  serviceAccountName: system-upgrade

  # Specify which node taints should be tolerated by pods applying the upgrade.
  # Anything specified here is appended to the default of:
  # - {key: node.kubernetes.io/unschedulable, effect: NoSchedule, operator: Exists}
  tolerations:
    - {key: kubernetes.io/arch, effect: NoSchedule, operator: Equal, value: amd64}
    - {key: kubernetes.io/arch, effect: NoSchedule, operator: Equal, value: arm64}
    - {key: kubernetes.io/arch, effect: NoSchedule, operator: Equal, value: arm}
    - {key: arm, operator: Exists}

  prepare:
    # Since v0.5.0-m1 SUC will use the resolved version of the plan for the tag on the prepare container.
    # image: rancher/k3s-upgrade:v1.17.4-k3s1
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  upgrade:
    image: rancher/k3s-upgrade