{{- $appName := "external-dns" -}}
{{- if and (eq .Values.group "infrastructure") (eq (include "cluster-apps.enabled" (dict "appName" $appName "root" $)) "true") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: argocd
spec:
  project: default

  destination:
    namespace: external-dns
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.21.1

      helm:
        releaseName: external-dns
        valuesObject:
          provider:
            name: webhook #linode
            webhook:
              image:
                repository: ghcr.io/theoutdoorprogrammer/external-dns-firewalla-webhook
                tag: 1.1.0
              env:
                - name: FIREWALLA_HOST
                  value: "192.168.115.1"
                - name: FIREWALLA_PROVIDER_PORT
                  value: "8888"
                - name: FIREWALLA_HEALTH_PORT
                  value: "8080"
                - name: WEBHOOK_PORT
                  value: "8888"
                - name: METRICS_PORT
                  value: "8080"
                - name: SHARED_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: external-dns
                      key: FIREWALLA_SHARED_SECRET
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /ready
                  port: 8080
                initialDelaySeconds: 10
                timeoutSeconds: 5

          policy: sync
          txtOwnerId: rpi-k3s-cluster

          # env:
          #   - name: LINODE_TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: external-dns
          #         key: LINODE_TOKEN

          domainFilters:
            - cluster.rebelinblue.com

          managedRecordTypes:
            - CNAME

          sources:
            - traefik-proxy
            - ingress
            - service

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi

          serviceMonitor:
            enabled: true

    - path: {{ .Values.global.manifestsPath }}/{{ $appName }}/
      repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
{{- end }}
