{{- if and (eq .Values.group "infrastructure") (eq (include "cluster-apps.enabled" (dict "appName" "local-path-provisioner" "root" $)) "true") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default

  destination:
    namespace: local-path-storage
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  # fixme: convert to helm chart
  source:
    path: gitops/manifests/local-path-provisioner/
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
{{- end }}
