apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  releaseName: promtail
  interval: 5m

  chart:
    spec:
      chart: promtail
      version: 6.15.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      
  values:
    fullnameOverride: promtail

    pipelineStages:
      - cri: {}

    loki:
      serviceName: loki
      servicePort: 3100
      serviceScheme: http

    serviceMonitor:
      enabled: true

    volumes:
      - name: containers
        hostPath:
          path: /var/log/containers
      - name: pods
        hostPath:
          path: /var/log/pods

    volumeMounts:
      - name: containers
        mountPath: /var/log/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods
        readOnly: true

    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
---
apiVersion: v1
kind: Service
metadata:
  name: promtail-headless
  namespace: logging
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
spec:
  ports:
    - port: 3101
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promtail
  namespace: logging
  labels:
    app: promtail
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
    forecastle.stakater.com/appName: Dashboard
    forecastle.stakater.com/group: Logging
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: infra-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: promtail.cluster.rebelinblue.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: promtail-headless
                port:
                  number: 3101
  tls:
    - hosts:
        - promtail.cluster.rebelinblue.com
      secretName: promtail-tls
