---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode
  namespace: external-dns
spec:
  encryptedData:
    LINODE_TOKEN: AgAIP2eREhGvtf6gKjLxoBO5IJtUEOysKE5V/ZLQbzZHjc4XrjzhSsGiUhnBCfrrtPhBjmp1JV/sva9cnj2S4iC1/YESFqCT+UchcTzdPpN3xTxwwifl7elwPBsnjDdrfsq2lVv5xa7SUU9qb3f54jfWbko2jYlXyAdiXb0AFk/Q0MxX++aQKW1IHCYK9/4mFF780h6Jcunpqy2bBHD/gKCbeWXuVNVkjAPQMQ9PR48inzDTWE41BQgrvJfae7qxMHcSUsxp0RO2PoEVTS7TZgxGCnWXuycMNaoLo59/aa0KkuRAhDt22AYvPVVOfyACwxikDRnCs+Fe65KIoMLt3z9JAIb3shrXikriGWwksqGsnt/OEeqfEwiNt7WRRg+zc654xlxUlHN5KUYkVh7RHs+/Um2Od6RIVT6gtzMsRi3B0ebsAg4E5K6/zfPQLWU8OsYar0uqqRTvW0nHLMBTA0IRyRvCryqaksuqcRadk8laOuGOP/pK16kEWyr7gPZN6ZuA+h/LgL6YLc7o71OMlxlVtP9/FhP3MJfMwlhmCai1VCX3h1usaRu50yxv+2dmHJgqGdBD1zLSewLwbEkBJw40xpW9lYLrP7sh59VT3vVL0AmJ82XA+d2ZKDKguEB52B6cICWlP/lG4m8MMvbRNHzAINqJF8JIVLPwP+0pA+a9n2OlsgBFKM/exm0neeWWrElsta1BdshVWcJWQDeiBSpwlOXcdGRuyhlWbACHuimhEcNMUuc7+A4gstjdn5Iyy5trvgJIYxhDzgLWUtui5aj4
  template:
    metadata:
      name: linode
      namespace: external-dns
