---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode
  namespace: external-dns
spec:
  encryptedData:
    LINODE_TOKEN: AgA6DGrymbaDaxmOYZJ0lzqFlOxnHV8cX3Vsfbsq7M2aIfD3Awvn8B5YP/RqeM0WohrI/+L8AiifKbfRd+oQm/JdjR/6tbjeczjNT2dsodJfpRLpHqYy5kjMCPRv3hoI1QPAutg3cvVkwGVNU+B4RTm2aQ4jbX/6kOHPdrATuDW0N5qzS1g1vom2g7EhRzGAr6Mas5bRRO5Cn9zWiUFToDYHSytzt78xh5t+z0GvL6a9BJUwW4Bhj10U/FUVJAiulbqFNpN3JDjKEZXOCExAnH4DR+EQF43piM/IxqSNV2/ucV+Kyj5gSWmZeBfysmdYCaVKwQCvTiqQoMAd9UHnNUpGfjhTMcs2mOENFrbdS99v4IWaeWoQYFlt35NL7YfBHIPSb1Ow5ywgQKwotkIPXPFESzROirFd2YeVcalRmAdRB81pBQ9kkpe/gum4NZVCF7gtYP0WDHF1opkSE2H/f5SAU/0vyikVBwkCN6WomNzTYpS0zcbsrnL3qUfKcgn7v7+U1V8l4ksR+vtP+rkKq0EJg3N5pkFMYMslLkOXnXkr0L8051IKTUouE8ZaDLlb3J5Krghd1r1JoSLX8NrkTdvS/g1AJ4I4KFC+rh5WKgskBkgwi3abjjqRsMhwUv055QC5NvPed9WwHvV5bTLeYyDo4x+nQZAF0a75t4B8inY10XFf2gZ2u34playx91GiE05HdEc9nQAUBbXakYmnCoeYZbJmchN/wAcksaW0wS0OYTRKNBpYhrq2xXAB48vFCC35iKeSashYrj9X4swl0sK0
  template:
    metadata:
      name: linode
      namespace: external-dns
