---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode
  namespace: external-dns
spec:
  encryptedData:
    LINODE_TOKEN: AgBfZKMYDB290etvf8ruzu+PrOrtGD8/kAJKVTS+tQtDsLNsu89JFA5reEoKNLvTP1CCScetR/QABzmux9BHn+BX+2Z5uSYL8+iLCQ2wEJpJaKQLWUiebeUCUJs/YfnguvSz3MRcJRNTI1Ur91TnIKUFvdOGI6hhqhHQwCY2Hk+IHjuS35LETaDC7kx78wVKrqBFlbuhl7xr/XyA5vRi/NUlMr5RS/jlsv6qLgGxvkiR9rqYXmjIgjKHXXCPsklT5J3OhT+aLC86bfynGYOeLvr+WXPAejxCwN0NwzIv0uOmSUaSUerQEVlHjzz7mhYfZYQpQqHKNMblV0Xhm0jaryvMRM4S6bBVnRXkhfW/m9VaMT5PrR9Z4GjLo9rEKFYrI5eeyaYMjRvULOi9QvHY7d9h/3aO1czUdAy/34XpB8BrvC8hapolAQLUZOXzgG4agNkj7jDGnpO1A5ZQ2L0x1JrwsE84rM46RSfREZepY20z8LEIgn9RPdMPhFRWB69rl1eOTfJUgFIq0VU/EtjDF/noQSnjrAGtH+vEGFdpV/P8k7N8I29PvGFgMi7WMNFlpRomi2ko0HlFsMSJviTpT/3YAaHPFpkLUw68M0hV+MKZ916t/gRyjMIF5wsdTDGqLGC4ruL0/n52957e2CqaQ0QioJGiosbEYdrl5q4tUek21o2z28omCdKh/6WIG0IxECZw1Erc2SLWBUx1eAEpA2QvsBVrF28m6CJi/qkFW0tItHVJabjbePB2oB4kAD5jnaErPp4JQWSZDblt5JbWFMhX
  template:
    metadata:
      name: linode
      namespace: external-dns
