---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode-credentials
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAxwr0PKCyZbam/mLbGU0H6l/Z0RnRJ6Ho+RzzVbElxQJwm8tvKKFlyK+Lvp2MCMQAib50Pw30vFE2mxr+IKGSYiXgQG/L6b0l+mhPysfkT6FWJm8O69WB0L87BSyAl5hwtrELCkUULX5DE1LLO6/YgtiQiwhgjECRlaUYj/7EfQHI1orcL5kNr1yyqggV5OlAsPnZJgPVX+JbiyoQ0+TKYhe9UHgtRvNeRAZG1p3wdoXvkDyD8ZwaCLcvVrqYGefeDIoq9PSi3YKTGEVKlQpU89k8iNHBctARovP/RUov5VFjPtkJV5Emo9LIyr+XyxlsQ9bkaYGOEpKzOinke2Aztw/29QzLf1VAJLJsCbazc+AtIiRKGir4Pe3kwFIYpAb8RyOevuZ9WwqEdgux0Iu9X54DBFk9ar5WJy3syWJ+JdgEFvmO5HZHTE95nRY6uRz5ggLwyYB+Ddgbgxap0jm4qBzPoDfmcOedWpVb8Cq/J3DTf+9K1PLMLXNphiz1HbgA+VlnZwnYzK5tYbSvea1S370xM0vsUzK3WgnNgzyRGxHtI6C3uWIIgGtPXwsby9wbxJrZBSxSWYlHWup/GNwqS5fSZt1otyIX8ExVfDD3boAWcw3ksWZ8jg7KfijSRUDRHghranAFxL9zFvlpqRzNRX1KLfQTYO7VZ+ARridBXyk06jB9HBYAZpYgaXn1MqQkLJI2enZwHg8uM96fsMQgZMOiXfiru3JlTamUoDTrCXY5iDwGSgLpyuEznLX/kljpeUTeV3T4SL1oWw1NOEQJx
  template:
    metadata:
      name: linode-credentials
      namespace: cert-manager
