---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode-credentials
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBPQK8OTsM6RfRI0W+lxIDyF8UHE/1yaQW2LWMpWpJwI/5X2OGDAlqNS+t4hjKnXdonh23NSv3NjJTLFk9niv5S0dPfxVyAiV1gupZZ8RU8zyHGjb8k/kTpK+FXsmnyFtlL0Lk5dyYsGs26uxF+apjZmiAbs6OJeUnSYZqcjOSBGVUU6eFkOYQUj2bZQmKKDhRGE8lfaR9YTTHBJZHlzd60rT7q25lz0+6oKFPLiMRj3sT4NNPagwvOsFxk+uwpz5e4XKJNhj5acxlVxuiFQYKJ/ADlY7aJDw4nowkIbYAK/Xm9CMroIA41wWSJ1Dc4MSKz5MRQzy9bGFlnpSG4Lea1VOoMIJex+A2g80rKKB4CHszkc1un6mjKf6nl0viD9e7hu8FNqjKgYT4lHj3ONUkkGsfuCb378qJfOc/ZnRUYF4ZHO3KcmfLDhEADsfvOEajEjX1fAu8kraoN15hqozDIt6bREMs4wskEtyyze58MOC9so79IT8vZujJhkYhS7tJWvBZg5cjdlivQz2FXWq+FwmX48IceHvj4yIO8iLlujCstjFfei+eEaGAvXIb3JA1okVBdMtDy/CcTXHPl+PpMayIEadX7FeMj1IyAF7uOLleZZeDR9oZrPLQFzb95OMsGwm/Mb3en4HELrM/egeguEuRzjIxqwCg6iQR76uZtesAeO5Yq8nipxdbeAODBE3hlbyowtUVN2igml/6/WIwPXAm743AwI6BAnNLZl7Xi3xuVjxluNcTRcTiUD5uKQevVJb3Z/5y5UYFGnYkQ3siL
  template:
    metadata:
      name: linode-credentials
      namespace: cert-manager
