---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode-credentials
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCK1izQ01gvMPv5T54YInGwZNB3yPNkfKS7ztA+iWtOOe1gxBmm4txizth94eruhMo7lINxsgf/Dlpv1HR7r9B2a/YHW3cSK63zRhmBotbT+L+5GWfdjtA3pHKFm2LyNg3/QwmOWzzl5vi5jENHg0XrB9dtVqX29w9OjN7zV6iFfA1Kw7s0CpvtN+CffPVDyDaPdfntpcbwKYBZNE2/Z05VvKhAMtFc/Z/OkT0emnmKkRcvxUTgOgSoV9vvEa3y9SCyOpHP1VnwolZdEetf6+xrakoh0jNuZz+j2ZFthP2xbHNmdCQHbLAyEi9WB/eu26viT4Cn9swcubWIafUSvH6Aq0M8mpdD5rC35BeYX1OmhcVB96MO06Qi06/UDDiVjKpCX1MpM4N7LU/cK2EMu/7ELmsQclE/BtmBCEPWh9jzUTTHGnh8rLfUwRCeX12WCJM1hEwKtjw8bBq7K3VBkdi3cmk+xbmA/t5ttVDXq4LNdYWwB4hszx50o9GwC/XL5rsbr/FmIdd9ZM6dJtXabUxNVEBV+gTndIUbnp6BZ7crww1oY5C28FF0f1rKJqKT2wSXFgFdubl1a5lRAus+OtAxP0zD1QuSTkNc9UYWLCFeKwh/DiTbNudbcGnSAKvtivl8pDoYkvonLwxG2UdNwVClT+d3KqaiDRUGFA9Zh7ZpY70fvBYSugQl21MD2ZbdwFWXCzvyUkNTCH9cvl+Ji66+WORvugW8MI0FAitkh3Eq8j5lRSJH6RLMxhA8eQBODiMQmK1aOKl6d9z93GSTglst
  template:
    metadata:
      name: linode-credentials
      namespace: cert-manager
