fullnameOverride: velero

image:
  repository: velero/velero
  tag: v1.4.2

podAnnotations:
  SECRET_MINIO_ACCESS_KEY: /apps/shared/minio/accesskey
  SECRET_MINIO_SECRET_KEY: /apps/shared/minio/secretkey

initContainers:
  - name: init
    image: rebelinblue/vault-consumer:0.0.2
    command:
      - /bin/sh
      - -c
    args:
      - /entrypoint.sh confd &&
        source /env/secrets &&
        cp /tmp/config/cloud /credentials/cloud &&
        sed -i "s#MINIO_ACCESS_KEY#$MINIO_ACCESS_KEY#g" /credentials/cloud &&
        sed -i "s#MINIO_SECRET_KEY#$MINIO_SECRET_KEY#g" /credentials/cloud
    env:
      - name: VAULT_ROLE_ID
        valueFrom:
          secretKeyRef:
            key: role_id
            name: velero-approle
      - name: VAULT_SECRET_ID
        valueFrom:
          secretKeyRef:
            key: secret_id
            name: velero-approle
    volumeMounts:
      - name: cloud-credentials
        mountPath: /tmp/config
      - name: config
        mountPath: /credentials
      - mountPath: /env
        name: env
      - mountPath: /tmpfs
        name: podinfo
  - name: velero-plugin-for-aws
    image: rebelinblue/velero-plugin-for-aws:1.1.0
    volumeMounts:
      - mountPath: /target
        name: plugins

extraVolumeMounts:
  - name: config
    mountPath: /credentials

extraVolumes:
  - name: env
    emptyDir: {}
  - name: podinfo
    downwardAPI:
      defaultMode: 420
      items:
        - fieldRef:
            apiVersion: v1
            fieldPath: metadata.annotations
          path: annotations
  - name: cloud-credentials
    configMap:
      name: velero-aws
  - name: config
    emptyDir: {}

credentials:
  useSecret: false

metrics:
  serviceMonitor:
    enabled: true

configMaps:
  aws:
    data:
      cloud: |
        [default]
        aws_access_key_id = MINIO_ACCESS_KEY
        aws_secret_access_key = MINIO_SECRET_KEY

deployRestic: false

configuration:
  provider: aws
  extraEnvVars:
    AWS_SHARED_CREDENTIALS_FILE: /credentials/cloud
  backupStorageLocation:
    name: aws
    provider: aws
    bucket: velero
    config:
      region: minio
      s3ForcePathStyle: "true"
      s3Url: http://minio.infra.svc:9000
      publicUrl: https://minio.cluster.rebelinblue.com

schedules:
  daily-backup:
    schedule: "0 6 * * *"
    template:
      ttl: 120h
      storageLocation: aws
      includeClusterResources: true
      includedNamespaces:
        - '*'
      includedResources:
        - '*'

snapshotsEnabled: false
