---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: linode-dynamic-dns
  namespace: infra
  labels:
    app: linode-dynamic-dns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: linode-dynamic-dns
  template:
    metadata:
      annotations:
        SECRET_TOKEN: /apps/infra/linode-dynamic-dns/token
      labels:
        app: linode-dynamic-dns
    spec:
      initContainers:
        - name: init
          image: rebelinblue/vault-consumer:0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  key: role_id
                  name: linode-dynamic-dns-approle
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  key: secret_id
                  name: linode-dynamic-dns-approle
          volumeMounts:
            - mountPath: /env
              name: env
            - mountPath: /tmpfs
              name: podinfo
      containers:
        - name: dyndns
          image: rebelinblue/linode-dynamic-dns:0.6.2
          command:
            - sh
            - -c
          args:
            - source /env/secrets; linode-dynamic-dns -s "$(expr "$FREQUENCY" '*' 60)"
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          env:
            - name: FREQUENCY
              value: "15"
            - name: HOST
              value: ~
            - name: DOMAIN
              value: cluster.rebelinblue.com
            - name: IPV4_URL
              value: http://checkip.amazonaws.com/
          volumeMounts:
            - mountPath: /env
              name: env
      volumes:
        - name: env
          emptyDir: {}
        - name: podinfo
          downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
