
provisionerName: nfs-provisioner/nfs-hdd

image:
  repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: Always

nfs:
  server: 10.0.0.1
  path: /media/usb

storageClass:
  name: nfs-hdd
  defaultClass: false
