apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: infra
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: registry
  interval: 5m
  chart:
    spec:
      chart: registry
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      version: 2.1.0
  values:
    persistence:
      accessMode: 'ReadWriteOnce'
      enabled: true
      size: 10Gi
      storageClass: local-path

    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
