---
kind: Service
apiVersion: v1
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  selector:
    app: traefik-forward-auth
  ports:
    - port: 80
      targetPort: 4181
      protocol: TCP
