apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: linkerd-viz
  interval: 5m
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: 2.11.2
  values:
    fullnameOverride: linkerd-viz

    installNamespace: false

    #prometheusUrl: http://prometheus-k8s.monitoring.svc.cluster.local:9090
    #grafanaUrl: http://grafana.monitoring.svc.cluster.local:3000

    prometheus:
      enabled: true
    grafana:
      enabled: true
    dashboard:
      enforcedHostRegexp: ".*"
