---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode-credentials
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBVow18Bf1SRvg9DUH0Ky8lvjawuHvT2OUiJAqA3aARMp5tzSyqqH8KD/WpHECLV/rNi11Mobv32FEBBW5rtOsMM4IN9V9sjOnnZ9KoMZ4HB8KdUkArJYJVGkGMDfVARTFa93JgXhDHLx4o30ArRhrAWhMCoCneCY3XEmbQ0WljzRbC5IB1UagpA8aLF2Y9fKvvWlZDZQ0FS1cyZBwcUEruXaeBwx3uFGJZwSxkBKX0IagwuRKDCilnbDCH+cnIpd9i7QwBPMeUp2rTCdsuk8d6fqS1h87ybQ1uWePhuZVuIq6qccf67LZcbmRfCRrHs8CLTWJF4NAjEJMb1JAd4nygADZxyvCRzFu2/Tj+6DY/Nxo63TopUsiX3j8VUMz1ss+tcwWEzs+RjnxouoGDt1I/VLp07//RHDxuhqVuESaLL7iEvhMOEEUhhYqLf4jrMqIDsmU64Ix6cOZm/hYB+rgW+fsrr0+fMJzbQjVjXQO71aEqqR0BCnihiXyD6HzK+Yb3uwsZDvC8Pau67A37OcRuKJ81u4P9zeWDp+kO4atYDTt5YsXaVLKmH8NgeyRdZFbpCswjlQt0T+ifaJluxs2Zj8fDBJnElaahH1VLVTqnpj+8kwWVumQwyeHEVbgsotdpNbtpiVLGlqj7uHmz3UXoWhSBEqFnMCaOo1aw1EqTBbcFX7p+Eb80EbauufN8hh9xxIH2rUCQd7s01YMjEJMXaPTsgpUo4d0WNtEQ9/r4pYrP2eWZAZs3Mpsso3IAg0yRkoAHxV+h6HPcTc5WSEKf
  template:
    metadata:
      name: linode-credentials
      namespace: cert-manager
