---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode-credentials
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBXm3T8zd+esh4qH7e8M2oCt+sFYmHSYsk+hVw7y+CYPgaK8kpM5L7rj9lPStGn1ZiossXTs8drqYsJDivObD0WB5WzAaiTYnymufDzMD3i4opG7GpPxuQHJgAAVCu8+OvalvzNzFyznHbPuu80SzWJDJbB2BC4UZOWj3gKdj++ruu7Kb4cFXKNOIszsYg8MMbUwxw5AcuaFTj0rrujCAhfP58j5Jn2ETUg64bzzwKnGSA8Lt2v2ifx4xFEotesuF+5W8b/XJz9eD3J2ookhLDbC/QhB012eOofnZs6jNTj39yubcOk0DYdt5nCBpqV9e5MTOfoDIBilm89JE6X/4JSJJ8PnlRI5fxx2C7ZK5eXhJTWmdHL2CyGJlDH5fTfTjqDJ3MrL8eVHzUJEEaz5XxvJF/DGR0Y3IaSYtb75XdfaguIr/2guNLGSRq3LewlQCuA5hogbzR4ocsRQue0wkQ6O1lh1abNO/K+EJ40o9mCTrzpzahDnaMTzAeEJaLJmMPvmmqGrZDW/ArFWMHI3XzpxwU8UaK9FTLCMvj7MMOiNd/9oGrCErmW6ODLVLNe2Ne0VJ3gP5Kew6LTUlz2w9GIXFIEdIsZqgQbRLaMWCxdWp0tOb3kNRA1V/iacAw5DtmS0EFJ4p/uYZZ52r5is1I1aKkSoD1HwRyRQQPvpU3slRu9x7kJP2J3Gfy70V+OOXHDXvw1uNi0N1dXuiiAqUzScJq9KKgZGDMJZW7TslsJsPhN3eOyaXy8Pw+cFK3oVdjB0Lle77puSbBQZ4/hUxfw
  template:
    metadata:
      name: linode-credentials
      namespace: cert-manager
