---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linode-credentials
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBWm72XiIVRsO44HEogFwYZU0RxpvlTHUl5VtwzlFGYUeilTKBMy+72Wa88fHpyxVr7eA0V8lg0qoW3Qnkvi+tubKlj15c87fx6J1oH5duBOuJepMkZ3++gE8dlWbPdwVmLHSgQI8Umm447IuNFnCzSkckVP2B6RFGa2FlXZBbSHTPbisiWKYwuiSKqTwXeFUwMaBh83kEcTe/rYKhZVrYfldnqV5wCDmbIr7uF3Zat33kvKxakmTMYjlKgTi3LjNMhhbx4VVFPWYkuSvhegcpPXYaZDnrcEmS4C7S7wFhjHt9/jJcujq+f29THR8u+851oF4Gu4C04ZPvJiS1xiwOXTfzK14PCNJpvjQAGhJX/t9E+Ls9GmCdjDDNNb2L9BgBXHWP4NSy6uOPhakPgKpls8rqgpKAwSFHHagqR4X9M88IG9qamzzdVSwTPwU0QPhWlo3BIWKQVbhwSBEuuY3dbS+QFFFyEu1gwNGQv70fcR7tEn97z3j9cq9dlXeaOCqc3K+w8M0wqcWAZex8zi3Dq4hLW36fd9KGOTi2MxVyDXTsz4Y7EuNmOcjuiaU2ZLBCB2ddlam4ML4hDr3d3nOFJgGMNuXacFq2cGPpD3G99cfC+ir03pya5/Z35/9n1Ozr3VkjVJghVgJGx6VSJrE6V/YMbFs4+U6oubzig1UY25k4hVxwU61+fvSCGm7y7/aojqMR02i9zazBZY3Evum+usVK8y6O0kKhRLlsOx81gM3CDIUL4M18T360tirPrGlDWac12P1gbuxqz0Ll/N0Tp
  template:
    metadata:
      name: linode-credentials
      namespace: cert-manager
