apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeview
  namespace: apps
spec:
  releaseName: kubeview
  interval: 5m

  chart:
    spec:
      chart: ./deployments/helm/kubeview
      version: 0.1.13
      sourceRef:
        kind: GitRepository
        name: kubeview
        namespace: flux-system

  values:
    replicaCount: 1

    image:
      repository: rebelinblue/kubeview-arm
      tag: 0.1.14
      pullPolicy: Always

    nameOverride: kubeview

    ingress:
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/src/assets/logo.png
        forecastle.stakater.com/appName: KubeView
        forecastle.stakater.com/group: Infrastructure
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
      hosts:
        - host: kubeview.cluster.rebelinblue.com
          paths:
            - "/"
      tls:
        - secretName: kubeview-tls
          hosts:
            - kubeview.cluster.rebelinblue.com

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeview-images
  namespace: apps
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: kubeview.cluster.rebelinblue.com
      http:
        paths:
          - path: /img
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubeview
                port:
                  number: 80
          - path: /css
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubeview
                port:
                  number: 80
          - path: /js
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubeview
                port:
                  number: 80
  tls:
    - hosts:
        - kubeview.cluster.rebelinblue.com
      secretName: kubeview-tls
