---
- name: Check if backup exists
  ansible.builtin.stat:
    path: /boot/firmware/config.txt.bak
  register: config_bak

- name: Backup config before modification
  become: true
  when: not config_bak.stat.exists
  ansible.builtin.copy:
    remote_src: true
    src: /boot/firmware/config.txt
    dest: /boot/firmware/config.txt.bak
    mode: "0644"
    owner: root

- name: Copy config file
  become: true
  when: not config_bak.stat.exists
  ansible.builtin.template:
    src: config.txt.j2
    dest: "/boot/firmware/config.txt"
    mode: "0644"
    owner: root

- name: Reboot if config has changed
  when: not config_bak.stat.exists
  become: true
  block:
    - name: Include reboot role
      ansible.builtin.include_role:
        name: reboot
