---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    NOTIFY_URL: AgAZ+kyMRPPYWfteaHizXuUEbW93tUwikKVH9sFQFNHSsmR8GIm/r7SzGRZvR0uz2XRZE5/9rHlNQejQ2wOMyfMzKuOUly/MT6VqyJtvxOSrrEGxS/aihQyw26NN6fEI9NOe6kaPWrLhu6wJMMz+9kO0LXL21cnedlvksNtxl53wPBqLrLOeQgVrAR4hGZ/0mYzphDyfqCpfIuiLBq6TtIZSEQTrFhXaXHk2IEeM+LYaiLzqC73ILwz0lFFn6l/iGj3c8xP8owE9lofNZU/INFuWN5djAC6a66AOkAD9RwHP5mjyB9w6P8r8v+4oUljki5ifpQ7teqcYddMRkl95CUc1S6Po/1yQ+K4sr4I50h5JeCa+JUa+bEFEuwz73Y7E4HcZcQUKw36Z8mfskI/qH8i7hnLIOdJmThhi6n9t9drhSWeKA+fG1/9lqPwhw4piswJav4KJtWiL70PxLVMDJ3TUvnv0WBDN7jPbRH9TkRMRdAyKKkEK9n80i+gs5gxRGxVwyEyKvGDiejW82S5ueWcskG2yDblV2tAxf0ohUfsCydFfxZRpakgexPI9dyqp0ItepVUq4OOKQXjhFB2HwTZBTIcdoxuHIyUJzOBBTb18j8t9FYvdibS3LUhNNfaUm3lUa+wRu0Ok/GFOYuMXCmP3YuRC4lepqeMfgJaeQEjo+YM7stdA3iCT79/q+dPUOwDQ2YrhH+rJ9hqzXlLWtE4iW+tJ0yhmBBXohCbnkmuKwoDl2FfKpqyOxmONWXQTTDWy7GuajuRAGsxvFwGowZc1gUuACu1NWof3GyowLfft
  template:
    metadata:
      name: kured
      namespace: kube-system
