{{- if and (eq .Values.group "apps") (eq (include "cluster-apps.enabled" (dict "appName" "debugger" "root" $)) "true") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debugger
  namespace: argocd
spec:
  project: default

  destination:
    namespace: kube-system
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: gitops/manifests/debugger/
      repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
{{- end }}
