---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: ingress
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
        - image: thomseddon/traefik-forward-auth:2.2.0-arm
          name: traefik-forward-auth
          ports:
            - containerPort: 4181
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: AUTH_HOST
              value: auth.cluster.rebelinblue.com
            - name: COOKIE_DOMAINS
              value: cluster.rebelinblue.com
            - name: WHITELIST
              value: stephen.ball@gmail.com,stephen.ball@lendinvest.com
            - name: INSECURE_COOKIE
              value: "false"
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: CLIENT_ID
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: CLIENT_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: SECRET
          livenessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2
