apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-forward-auth
  namespace: ingress
spec:
  template:
    metadata:
      name: traefik-forward-auth
      namespace: ingress
  encryptedData:
    CLIENT_ID: AgDQg9ZXssAOCM7STvo8GKmxeUrjIAGpPnfcafeLpRThZS0wlKiXlv/pMlLiDj+x43uCS1Nvw11zf2fUxsgs2L90FwbhHtt2A4Qt+GVZN2BtKTSOwr+XjK22HfQNDUK5NPgRhDVZUZ3cI09PRy7aLdHdTBftbiF0kRY4XEEE9Lxo5d95Nv3S6+0LchcV4jTr/yRmRVHp5EpAwf7JAEarnfRqPbvzWoV73iLXNBJoV8wFdiAzImCSlXRWkgeXb5viEXIAt9TRwtb+zrafGHksYC8qjq7Yck0mWL/vyQi7lKczWwB75VlHsoNpxhuAnvFynjiS4h3RdcxNS9rLthFH994MtiDu9AaIKud/Nfk79239gXUXkmbj7cucVsaGUAQZ+deRTGwZitXfPQmBBfC/l8TPW50gOwBqXxShgHFd6Xzr1a3bOMnfTpk0VOwlAmVEUUuXBkzIwkMQPRZLKmKwrmc0r7XGgy0OCmon42Hs/mOiKIMW29GWCPxInpBUw/qbewm4wTuv5/NNhiHwmeh/mFSNSqosqB1BOI89t4bbZ44ey2GPKE1tOkulnYrj1K5A1sCXJWgJptxVX37hOJFOOPa0Km8Vyy3mY6wsYEeCrlugP9v6o6gItz4Tqx5glgL5cwFcEyxLQG3xEzXMxOZAhVL5/u6rsU3MuqEO2f2gvPaV+0PGmywqgFl8A7ucobUmsH5CS4MetRjHKuqcYxGpKGX0q5M0oy9KGTh2szNW2i1t5A71g0uZErotdA4D3t+WfVKUxHjhXKTvQOvP+D30kebSU2vWcPJfM8I=
    CLIENT_SECRET: AgAN4W6HSRkH+XvU0t7Kth+E+MWVS9TI2vrfLaQ7Kucter60kmMXjo5rZequcWBXScQXfYO/jguXo4KjmR41u6MgqN71+WLi2bE6ehP8TLsu7KUY0RryuI0A2CRQpG1ZYvlopzMkoToRxPYt4JmLVcyPExZvtqP5WMbfYJQ4f5I/XlNJ0d5ZGmx0fm3snI1rMpOE/NQSygKgRCcfUHPRJRsZPLqEV7IR9uM8S76MQgDBEDqUsBqS0E6ESaLJGIFNOXUETa5rv0Jaai68GMn5OVGkcQL5zlpS94R9ThDhp37FQGymOIQTcUZFRZI6qMgha5jtHjI/yXL9c37gPiecYu5mwRIDFPC3nSNiCf32yX+OIhMsg1KH7CrABEXiDSsJWSYgzE1jbxumPFLpfQ35Nm3WvgA1nt0PTq+qquSdhq8Is+SMLN3YwORTJH3eNosFDTm7dti6qpxq5kTAcIbWWy9QBR7YN+yhByGAvb0wROrvaxHhrIUjuvYOuy84ONxmhqzYMeKycbYwANwYNs7hl/muD9V0Wh1dMUP33C+PI0TY8tExfKj97ktdp6nwYcKW0OoF+QuJx4UGgCOBUydc8o01m7F4T2F607/yib8fXd2pcKCb1L9iyDZEUHW1ezqy0ZHmr5OHXyH1ZK7uS0P4FuKa/mQrT2s8OvsSxrBzEQW+YB/1tDIHwH0IUcu+/ZrctImgamP3qspWhZMnRDspuYXffLt0L1l5snJX2FthJeAyccRcXA==
    SECRET: AgCiOFLXZHrDO6r+ML4Uf8no2XX9DTX76jm3zSsZBs3cG/jG1+8RJN6vslnRn6GR+A4kLiCfX5wTO2wwq3Oq5EUq/i8jaK2FMFRMVLNVlSIZGKUQnlZXLRarC32GsUVs338hvvY07qFT9BxRLOy7qsXqHgZQEWQyh76IS5EIUsyAvmQd799cG9Tc/TpQnOBt0XXmsiz11/N4QblS9rFUp2sd69yJsp9870rYqebODBx1r9RckHrpvCqhW2U+jQtlhEfZD98qy+dtLRGrbH+hScJeVe5Qiz7VXKn06VQFbfndyXAsRy+o/kvN4qflg7n5OAYG0AC1bzqkYT0LPr4TgRutDQKg0r45vZKPc4NoyVKl8iiFpUTh1wJmUCbYOyJSTTyopudC3zgdooq9D+MEHQG5PsSG1VP6EygSlY5Iz/D4MjKLjcxoWVBbiHcA16XxFiP7oZ6yg5mLchMx/BrxbMN+3TMM+qx59AEXelCwCptnia61x9IVnbTAoeL7+JMJdCIRfC0mkmnf/SlVob28XWvdpODdxR/ALNReCS6X7RrooOs7sWiOZzZJhFInHsFi76GiEK4Ok6WZ0U5oLvElsW89awLxbRViiAcxWaHIrY896KfDt9O1IXMyEh2XjbKzwgBROh8Jv2aGbfxe8nPqTjULFw2XLWevQU+l8gaBgErvoO1qn/nh14tus4tiS+EJayurI5UUAb7eAymidlouQC5UYkRgs9x6G3U=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: ingress
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
        - image: thomseddon/traefik-forward-auth:2.2.0-arm
          name: traefik-forward-auth
          ports:
          - containerPort: 4181
            protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: AUTH_HOST
              value: auth.cluster.rebelinblue.com
            - name: COOKIE_DOMAINS
              value: cluster.rebelinblue.com
            - name: WHITELIST
              value: stephen.ball@gmail.com,stephen.ball@lendinvest.com
            - name: INSECURE_COOKIE
              value: "false"
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: CLIENT_ID
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: CLIENT_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: SECRET
          livenessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-forward-auth
  namespace: ingress
spec:
  selector:
    app: traefik-forward-auth
  ports:
    - port: 80
      targetPort: 4181
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-forward-auth
  namespace: ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: auth.cluster.rebelinblue.com
      http:
       paths:
          - backend:
              service:
                name: traefik-forward-auth
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - auth.cluster.rebelinblue.com
      secretName: auth-tls