{{- if and (eq .Values.group "apps") (eq (include "cluster-apps.enabled" (dict "appName" "kubeview" "root" $)) "true") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeview
  namespace: argocd
spec:
  project: default

  destination:
    namespace: kubeview
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    # - chart: kubeview
    #   repoURL: https://code.benco.io/kubeview/deploy/helm
    #   targetRevision: 2.0.6

    - path: deploy/helm/kubeview/
      repoURL: https://github.com/rebelinblue/kubeview/
      targetRevision: probe-values #2.2.0

      helm:
        releaseName: kubeview

        valuesObject:

          livenessProbe:
            initialDelaySeconds: 30

          readinessProbe:
            initialDelaySeconds: 30

          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Exists

          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"

          ingress:
            enabled: true
            host: kubeview.cluster.rebelinblue.com
            tlsSecretName: kubeview-tls
            className: traefik
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: {{ include "cluster-apps.certManagerIssuer" (dict "appName" "kubeview" "root" $) }}
              traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
{{- end }}
