{{- if eq .Values.group "apps" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default

  destination:
    namespace: default
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: podinfo
      repoURL: oci://ghcr.io/stefanprodan/charts/podinfo
      targetRevision: 6.15.0

      helm:
        releaseName: podinfo
{{- end }}
