apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  valuesContent: |-
    global:
      domain: argocd.cluster.rebelinblue.com
    # FIXME: Remove this? https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#ssl-passthrough
    configs:
      params:
        server.insecure: true
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      ingress:
        enabled: false
        ingressClassName: traefik
        tls: true
        annotations:
          #forecastle.stakater.com/expose: "true"
          #forecastle.stakater.com/icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/prometheus.png
          #forecastle.stakater.com/appName: Prometheus
          #forecastle.stakater.com/group: Monitoring
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
#---
#apiVersion: helm.cattle.io/v1
#kind: HelmChart
#metadata:
#  name: argoapps
#  namespace: argocd
#spec:
#  repo: https://argoproj.github.io/argo-helm
#  chart: argo-apps
#  targetNamespace: argocd
#  valuesContent: |-
#    applications:
#      infrastructure:
#        namespace: argocd
#        finalizers:
#          - resources-finalizer.argocd.argoproj.io
#        project: default
#        destination:
#          namespace: argocd
#          name: in-cluster
#        source:
#          path: manifests/infrastructure
#          repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
#          targetRevision: argo
#        syncPolicy:
#          automated:
#            prune: true
#            selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    namespace: argocd
    name: in-cluster

  source:
    path: manifests/infrastructure/apps
    repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
    targetRevision: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
