apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-system/sealed-secrets.yaml
  - ./local-path-provisioner/
  - ./cert-manager/
  - ./ingress/
  - ./flux-system/
  - ./logging/
  - ./kube-system/metrics-server.yaml
  - ./monitoring/
  - ./kube-system/kured.yaml
  #- system-upgrade-controller.yaml