apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - ./cert-manager/
  - ./ingress/
  - weave-gitops.yaml
  - ./longhorn-system/
  - ./logging/
  - metrics-server.yaml
  - kured.yaml
  - ./monitoring/
  #- system-upgrade-controller.yaml