apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - cert-manager.yaml
  - traefik.yaml
  - traefik-forward-auth.yaml
  #- weave-gitops.yaml
  - longhorn.yaml
  - loki.yaml
  - promtail.yaml
  - metrics-server.yaml
  - eventrouter.yaml
  - kured.yaml
  - system-upgrade-controller.yaml