apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  releaseName: loki
  interval: 5m

  chart:
    spec:
      chart: loki
      version: 5.40.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system

  values:
    fullnameOverride: loki

    ingress:
      enabled: false

    # monitoring:
    #   rules:
    #     enabled: false

    #   serviceMonitor:
    #     enabled: true
