---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.5.3
  values:
    networkPolicies:
      type: "k3s"

    persistence:
      defaultClass: true

    longhornManager:
      log:
        format: json

    # ingress:
    #   enabled: true

    #   ingressClassName: traefik

    #   host: longhorn.cluster.rebelinblue.com

    #   tls: true

    #   tlsSecret: longhorn-tls

    #   path: /

    #   annotations:
    #     kubernetes.io/tls-acme: "true"
    #     cert-manager.io/cluster-issuer: letsencrypt
    #     traefik.ingress.kubernetes.io/router.middlewares: infra-forward-auth@kubernetescrd

