apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  interval: 5m

  chart:
    spec:
      chart: metrics-server
      version: 6.6.3
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system

  values:
    image:
      repository: rancher/metrics-server@sha256
      tag: 08d60c68441e79443bedf42faf2e51b2f75a7c24a8f916c4de442d8f9b70c6cf

    # containerSecurityContext:
    #   enabled: false
    #   readOnlyRootFilesystem: true
    #   runAsNonRoot: false

    # command:
    #   - /metrics-server

    # extraArgs:
    #   kubelet-insecure-tls: true
    #   kubelet-preferred-address-types: InternalIP
    #   cert-dir: /tmp

    # extraVolumes:
    #   - name: tmpdir
    #     emptyDir: {}

    # extraVolumeMounts:
    #   - name: tmpdir
    #     mountPath: /tmp


    #priorityClassName: system-node-critical

    metrics:
      enabled: false

    serviceMonitor:
      enabled: false