---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  releaseName: traefik
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 10.20.1
  values:
    providers:
      kubernetesCRD:
        enabled: true

      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true

    service:
      type: NodePort
      externalIPs:
        - 192.168.115.193

    logs:
      general:
        level: DEBUG
      access:
        enabled: true

    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable

    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"

    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 200m
      meomry: 384Mi

    ports:
      traefik:
        expose: true
        port: 9000
      web:
        hostPort: 80
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
        hostPort: 443

    pilot:
      enabled: false
      dashboard: false

    ingressRoute:
      dashboard:
        enabled: true

    metrics:
      prometheus:
        enabled: true