apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-forward-auth
  namespace: ingress
spec:
  template:
    metadata:
      name: traefik-forward-auth
      namespace: ingress
  encryptedData:
    CLIENT_ID: AgAHzcz0JHKB50dH/vjczK8IhB2s9IHt3hKbokj7efxhebawkzwPsJsDYucjgzMj47Pxp8s4wI7xEU1ynhLo5qC5ZY9VogX1xxwU1c1YFCdwxwLuyjSYn21kv9rHEDgTO4n2FNm0ly0VKbxDpiEksNJgQO0IhV2+DXy3duFaj0+pK23GHWYj2TA+Blegq0O4Y9n9Vl3y1UYAzeFxSwISKxeNHVIgZOCw+eBQOI+juzjxnc8xYqzOBHD4uAF6Mv+KDtg3am6bOfwAOgwmfjekW18RG9D+V6PvPGU1Dnk23yiJZqWlYO6t1YOg0a+tk7eunvppZGxm+++FcBq6fKhLG9b1ijWKn7Bp6rdctJM1CcDD0lu/Id7Ve6RkpKGtBzWSaxa3d4hjZsy+tOlzZxnO7aLG3F0W/nG8OmmCM4+euJDPmIf5GhWWUnbZ7q560DfVS5gf0KEXWn8iWXCW4EB6ndMK1LA6t5zPpF2aHSlWPPpNA3av40h3BweA2sExDxhtEKM+frpjcvPAudWXASqnJv2G3ug427k/2tXUwFOsi0WeIwH8nLrc/N6K99sJDMuVZ55WmgAjEANp/4Oicvduxa8Tqu93wQFdDzroqMW8QMfEwHZ80B9FlWGWKicHQ32noy2YywjlHEmP+zSNo0BNBZp21Sw+KirriASJTVun8fqIZhI3EbvBYATAWBGajjAKa9UrmG/293CxEnd6/XX+NzHt33qOY0sdGXlhqW5hGv6pbj2LcqPm4w6BYHCotEbCsRrVhtW4VF6t7e3EZXVKxT4GyPmasFv3ut8=
    CLIENT_SECRET: AgBDGJPMkNRdQOfbXA3xwEOwizd2GkH8//cBYZ8F6gv4csKzYbQfmNsz1KqyHc0qkGevOFfw7RWNhfmKXXlPRkxOzxPxXI73/9LRmOO0P6iuSdxpJlGXWcPNh7qpP5FbRbWCycCtczmQf9Gpwft1b7W8exemz19nNXldjYZBdXIR0m6baNILpwzECSuYUWExMFXYwApcrurp6GLuU2eO+9NqFE+pG8yFxzvScHtcpPtGUvla3F6OVe3+yAQnSBzEBKg390aQJKC8+7W2NJhrWyozkTTYqVjB5IV9C8usfUQbVfpLY7fFH7lAudTm1SYIEj4vJ6JZ+o9WwCDRTfUvKvueROfcZA4z56Z5joVw/aKjT39xjLLXU5t01Rq8MQkWNbA66+Tc+/c7XRFQPXfVnpQ0hv4O32oJkph5lJEZQzVaS8S/W2h5geOZ4yzL+OUnaYTGbeN1AgisyjoHOfK8GIVXNE6OSrwyWrUEbPtylK+h7+bzjdE94cz2FyTcg6QZ/3Fmwanth9uFee/IeEtgvRqveYACj2yXZapkBJmRqrhCK/4++coyUoh7YyGooMXZb7mdcH+Z7d+PPW8F/EnvETUbJzcUAZXxl+6qWT1PbpCwRk7xDK/w3VWOG0JYMPyJkKGHJBvmFZ0O5gGugg2rNL6RZbcIGDOzQft+jEgzfosS7PQosouTnIUKxX8DJgIsP8l1AA76Ns+LbDEgsEMAnrfYKejA4iLlVsF5Fj8vP/yS5SZAxw==
    SECRET: AgBLAKs5rNWGBKn+kmV9lqauXO9B1hSNv9lBetqWDUkzNIWmkRY6LotGFMhIt5HqMI7cHE5oFqGZRkzoxd07M+uGkKN3TPNd5e4qaEO0UTU/6VWTKzjFKwTDJ67f1du4d6j36JZ/0xKGeRZSYJIq/En0oPSPviD/YmPvry93YMnrGPBVlIB8QMG8y5jdcX6b3gZpM8YjZVNTWgcsJa55UH05U+ylv8m+4Xt3RRTweaNWOb7ujnQZXuCan1iIddIH5mjYVhA2QO+kAoHR5jF8vQp5FWzbky9jYEp9jmSf/pw0I4ivL/BBLStc1//rJ8BOo1exvK54w04tpQoTeKcYF6WTdNAxDD5fHHs2FaWiX/4eitxLaPbKycH46wz0C1iSZzq2kg1jJouCHO+R5VejtgbiTJ+eLZWNOmyFIY9rhtgphJQgBFFCuiRr/bGtvmmWpTthg0jeBZ3nwGouKTm8X8PMDKa3+RXh1joYasis6avP7s3AtPzfUo1/kB+bg0LrSFv6/L/a1Ms8ZoQ/mmep2oPWRgi/UNh4r7tzQsP2NiFuufTC1GegbysvzU24hHBwMshQjL02Z2/MbdvvqMSVKu58VS/Z5EjfwFd0fn1ms8BwpgMm5iaDp0puIdvCTFo/qmTGeHF90amX1+7YG8D6ZyK6ZuNMxKNpK+JxrRN6UjpJGIiwUCYa3E6dG84K73BcwnRbtzkHAl1+5ytH+r3i+ocHJUb14XRLwYs=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: ingress
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
        - image: thomseddon/traefik-forward-auth:2.2.0-arm
          name: traefik-forward-auth
          ports:
          - containerPort: 4181
            protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: AUTH_HOST
              value: auth.cluster.rebelinblue.com
            - name: COOKIE_DOMAINS
              value: cluster.rebelinblue.com
            - name: WHITELIST
              value: stephen.ball@gmail.com,stephen.ball@lendinvest.com
            - name: INSECURE_COOKIE
              value: "false"
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: CLIENT_ID
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: CLIENT_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: SECRET
          livenessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-forward-auth
  namespace: ingress
spec:
  selector:
    app: traefik-forward-auth
  ports:
    - port: 80
      targetPort: 4181
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-forward-auth
  namespace: ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: auth.cluster.rebelinblue.com
      http:
       paths:
          - backend:
              service:
                name: traefik-forward-auth
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - auth.cluster.rebelinblue.com
      secretName: auth-tls