apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  releaseName: weave-gitops
  interval: 5m

  chart:
    spec:
      chart: weave-gitops
      version: 4.0.35
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system

  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    adminUser:
      create: true
      username: admin
      # Change password by generating a new hash with:
      # https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-a-cluster-user-account
      # bcrypt hash for password "flux"
      passwordHash: "$2a$10$P/tHQ1DNFXdvX0zRGA8LPeSOyb0JXq9rP3fZ4W8HGTpLV7qHDlWhe"

    ingress:
      enabled: false
      className: traefik
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
      hosts:
        - host: weave-gitops.cluster.rebelinblue.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: weave-gitops-tls
        hosts:
          - weave-gitops.cluster.rebelinblue.com