apiVersion: v1
repositories:
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/stable-index.yaml
    certFile: ""
    keyFile: ""
    name: stable
    password: ""
    url: https://charts.helm.sh/stable
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/fluxcd-index.yaml
    certFile: ""
    keyFile: ""
    name: fluxcd
    password: ""
    url: https://charts.fluxcd.io
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/flagger-index.yaml
    certFile: ""
    keyFile: ""
    name: flagger
    password: ""
    url: https://flagger.app
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/bitnami-index.yaml
    certFile: ""
    keyFile: ""
    name: bitnami
    password: ""
    url: https://charts.bitnami.com/bitnami
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/azure-marketplace-index.yaml
    certFile: ""
    keyFile: ""
    name: azure-marketplace
    password: ""
    url: https://marketplace.azurecr.io/helm/v1/repo
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/openfaas-index.yaml
    certFile: ""
    keyFile: ""
    name: openfaas
    password: ""
    url: https://openfaas.github.io/faas-netes
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/eks-index.yaml
    certFile: ""
    keyFile: ""
    name: eks
    password: ""
    url: https://aws.github.io/eks-charts
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/jetstack-index.yaml
    certFile: ""
    keyFile: ""
    name: jetstack
    password: ""
    url: https://charts.jetstack.io
    username: ""
  - caFile: ""
    cache: /var/fluxd/helm/repository/cache/loki-index.yaml
    certFile: ""
    keyFile: ""
    name: loki
    password: ""
    url: https://grafana.github.io/loki/charts
    username: ""
