apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debugger
  namespace: argocd
spec:
  project: default

  # Move to apps not infrastructure, along with podinfo

  destination:
    namespace: kube-system
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: gitops/manifests/debugger/
      repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
      targetRevision: main

