apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default

  destination:
    namespace: logging
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: alloy
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.5.0

      helm:
        releaseName: alloy

        valuesObject:
          alloy:
            mounts:
              varlog: true

          serviceMonitor:
            enabled: true
