apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default

  destination:
    namespace: external-dns
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.12.1

      helm:
        releaseName: external-dns
        valuesObject:
          policy: sync
          domainFilters:
            - cluster.rebelinblue.com
          provider:
            name: linode
          env:
            - name: LINODE_TOKEN
              value: "YOUR_LINODE_API_KEY"


        #        args:
        # - --source=service # ingress is also possible
        # - --policy=upsert-only # prevents ExternalDNS from deleting any records, set --policy=sync to enable full synchronization (including deletions)
        # - --domain-filter=example.com # (optional) limit to only example.com domains; change to match the zone created above.
        # - --provider=linode
        # env:
          # - name: LINODE_TOKEN
          #   value: "YOUR_LINODE_API_KEY"

