apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default

  destination:
    namespace: external-dns
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.12.1

      helm:
        releaseName: external-dns
        valuesObject:
          policy: sync

          domainFilters:
            - cluster.rebelinblue.com

          provider: linode

          env:
            - name: LINODE_TOKEN
              value: "b148e05b3eb12a844ead87c949fe28d8742b6f2bdd9fde3a22742a55bc0e07bf"

          serviceMonitor:
            enabled: false

