apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  destination:
    namespace: logging
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.3.1

    helm:
      releaseName: grafana

      valuesObject:
        persistence:
          type: pvc
          enabled: true

        # DO NOT DO THIS IN PRODUCTION USECASES
        adminUser: admin
        adminPassword: adminadminadmin
          # CONSIDER USING AN EXISTING SECRET
          # Use an existing secret for the admin user.
        # admin:
        ## Name of the secret. Can be templated.
        #  existingSecret: ""
        #  userKey: admin-user
        #  passwordKey: admin-password

        service:
          enabled: true
          type: ClusterIP

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                orgId: 1
                url: http://loki-gateway.meta.svc.cluster.local:80
                basicAuth: false
                isDefault: false
                version: 1
                editable: false
