apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default

  destination:
    namespace: logging
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.39.0 # TODO: Update

    helm:
      releaseName: loki

      valuesObject:
        ingress:
          enabled: false

        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false

          rules:
            enabled: true

          serviceMonitor:
            enabled: true
