apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default

  destination:
    namespace: logging
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.48.0

    helm:
      releaseName: loki

      valuesObject:
        ingress: # fixme: enable this
          enabled: false

        monitoring:
          serviceMonitor:
            enabled: true

        storage:
          bucketNames:
            chunks: loki_chunks
            ruler: loki_ruler
            admin: loki_admin
          type: filesystem

        test:
          enabled: false
