apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default

  destination:
    namespace: kube-system
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.13.0

    helm:
      releaseName: metrics-server

      valuesObject:
        # FIXME: Resources
        
        metrics:
          enabled: true

        serviceMonitor:
          enabled: true
