apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 55.0.0

      helm:
        releaseName: prometheus
        valueFiles:
          - $values/manifests/infrastructure/values/prometheus/components.yaml
          - $values/manifests/infrastructure//values/prometheus/operator.yaml
          - $values/manifests/infrastructure/values/prometheus/alertmanager.yaml
          - $values/manifests/infrastructure/values/prometheus/prometheus.yaml
          - $values/manifests/infrastructure/values/prometheus/grafana.yaml
          - $values/manifests/infrastructure/values/prometheus/rules.yaml

    - repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
      targetRevision: argo
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
