apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    chart: prometheus-adapter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.9.0

    helm:
      releaseName: prometheus-adapter

      valuesObject:
        prometheus:
          url: http://prometheus-kube-prometheus-prometheus.monitoring:9090

