apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.0.0

    helm:
      releaseName: prometheus
      valueFiles:
        - manifests/infrastructure/values/prometheus/components.yaml
        - manifests/infrastructure//values/prometheus/operator.yaml
        - manifests/infrastructure/values/prometheus/alertmanager.yaml
        - manifests/infrastructure/values/prometheus/prometheus.yaml
        - manifests/infrastructure/values/prometheus/grafana.yaml
        - manifests/infrastructure/values/prometheus/rules.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
