apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  source:
    chart: prometheus-pushgateway
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 2.4.2

    helm:
      releaseName: pushgateway

      valuesObject:
        extraArgs:
          - --web.enable-admin-api

        service:
          port: 9091
          targetPort: metrics

        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi

        ingress:
          enabled: true
          className: traefik
          path: /
          pathType: ImplementationSpecific
          annotations:
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/prometheus.png
            forecastle.stakater.com/appName: Push Gateway
            forecastle.stakater.com/group: Monitoring
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
          hosts:
            - pushgateway.cluster.rebelinblue.com
          tls:
            - secretName: pushgateway-exporter-tls
              hosts:
                - pushgateway.cluster.rebelinblue.com

        serviceMonitor:
          enabled: true

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
