apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  destination:
    namespace: traefik
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 41.4.0

      helm:
        releaseName: traefik

        valuesObject:
          providers:
            kubernetesIngress:
              publishedService:
                enabled: false
              ingressEndpoint:
                hostname: dmzjrebqnjm.d.firewalla.org
                ip: 192.168.115.193

          service:
            spec:
              type: NodePort
              externalIPs:
                - 192.168.115.193

          accessLog:
            enabled: true

          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Exists

          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"

          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 384Mi

          ports:
            traefik:
              expose:
                default: true
            web:
              hostPort: 80
              http:
                redirections:
                  entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true
            websecure:
              hostPort: 443

          # FIXME: Double check this
          metrics:
            prometheus:
              service:
                enabled: true

    - path: manifests/infrastructure/manifests/traefik/
      repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
      targetRevision: main
