apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  destination:
    namespace: ingress
    name: in-cluster

  sources:
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 10.20.1

      helm:
        releaseName: traefik

        valuesFiles:
          - $values/manifests/infrastructure/values/traefik.yaml

    - path: manifests/infrastructure/manifests/traefik/
      repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
      targetRevision: argo
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
