apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default

  destination:
    namespace: ingress
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 37.4.0

      helm:
        releaseName: traefik

        valuesObject:
          providers:
            kubernetesIngress:
              publishedService:
                enabled: false

          additionalArguments:
            - "--providers.kubernetesingress.ingressendpoint.ip=192.168.115.193"

          service:
            type: NodePort
            externalIPs:
              - 192.168.115.193

          logs:
            general:
              level: INFO
            access:
              enabled: true

          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
            - effect: NoSchedule
              key: node.kubernetes.io/unschedulable

          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"

          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            cpu: 200m
            meomry: 384Mi

          ports:
            traefik:
              expose:
                default: true
            web:
              hostPort: 80
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
            websecure:
              hostPort: 443

          metrics:
            prometheus:
              service:
                enabled: false

    - path: manifests/infrastructure/manifests/traefik/
      repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
      targetRevision: argo
