apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - kind: "Secret"
        jsonPointers:
          - /data/admin-password
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/metadata/annotations/checksum~1secret
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: 0.91.2

      helm:
        releaseName: vm

        valuesObject:
          argocdReleaseOverride: victoria-metrics

          # VictoriaLogs Agent
          vlagent:
            enabled: true
            spec:
              k8sCollector:
                enabled: true

          # VictoriaMetrics
          vmsingle:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - metrics.cluster.rebelinblue.com
              path: /
              tls:
                - secretName: metrics-ingress-tls
                  hosts:
                    - metrics.cluster.rebelinblue.com

          # VictoriaTraces
          vtsingle:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - traces.cluster.rebelinblue.com
              path: /
              #path: /select/vmui/
              tls:
                - secretName: traces-ingress-tls
                  hosts:
                    - traces.cluster.rebelinblue.com
            spec:
              retentionPeriod: 3d
              storage:
                resources:
                  requests:
                    storage: 10Gi

          alertmanager:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - alertmanager.cluster.rebelinblue.com
              path: /
              tls:
                - secretName: alertmanager-ingress-tls
                  hosts:
                    - alertmanager.cluster.rebelinblue.com

          # VictoriaLogs
          vlsingle:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - logs.cluster.rebelinblue.com
              #path: /select/vmui/
              path: /
              tls:
                - secretName: logs-ingress-tls
                  hosts:
                    - logs.cluster.rebelinblue.com
            spec:
              retentionPeriod: 30d
              storage:
                resources:
                  requests:
                    storage: 10Gi

          grafana:
            # ingress:
            #   enabled: false
            #   # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
            #   # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
            #   # ingressClassName: nginx
            #   # Values can be templated
            #   annotations:
            #     {}
            #     # kubernetes.io/ingress.class: nginx
            #     # kubernetes.io/tls-acme: "true"
            #   labels: {}
            #   path: /
            #   pathType: Prefix
            # hosts:
            #   - grafana.domain.com
            # # -- Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
            # extraPaths: []
            # # - path: /*
            # #   pathType: Prefix
            # #   backend:
            # #     service:
            # #       name: ssl-redirect
            # #       port:
            # #         name: service
            # tls: []
            # #  - secretName: grafana-ingress-tls
            # #    hosts:
            # #      - grafana.domain.com

            plugins:
              - victoriametrics-metrics-datasource
              - victoriametrics-logs-datasource

          defaultDashboards:
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true
