apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - kind: "Secret"
        jsonPointers:
          - /data/admin-password
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/metadata/annotations/checksum~1secret
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: 0.91.2

      helm:
        releaseName: vm

        valuesObject:
          argocdReleaseOverride: victoria-metrics

          # # VictoriaLogs Agent
          vlagent:
            enabled: true
            spec:
              k8sCollector:
                enabled: true

          # VictoriaTraces
          vtsingle:
            enabled: true
            spec:
              retentionPeriod: 3d
              storage:
                resources:
                  requests:
                    storage: 10Gi

          # VictoriaLogs
          vlsingle:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - logs.cluster.rebelinblue.com
              tls:
                - secretName: vlsingle-ingress-tls
                  hosts:
                    - logs.cluster.rebelinblue.com
            spec:
              retentionPeriod: 30d
              storage:
                resources:
                  requests:
                    storage: 10Gi

          grafana:
            plugins:
              - victoriametrics-metrics-datasource
              - victoriametrics-logs-datasource

          defaultDashboards:
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true
