apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name:  pushgateway
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: pushgateway
  interval: 5m
  chart:
    spec:
      chart: prometheus-pushgateway
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: 1.18.2
  values:
    fullnameOverride: pushgateway

    image:
      repository: prom/pushgateway
      tag: v1.4.2

    extraArgs:
      - --web.enable-admin-api

    ingress:
      enabled: true
      className: traefik
      path: /
      pathType: ImplementationSpecific
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: infra-forward-auth@kubernetescrd
      hosts:
        - pushgateway.cluster.rebelinblue.com
      tls:
        - secretName: pushgateway-exporter-tls
          hosts:
            - pushgateway.cluster.rebelinblue.com

    serviceMonitor:
      enabled: true
