---
apiVersion: v1
kind: Service
metadata:
  name: promtail-headless
  namespace: logging
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
spec:
  ports:
    - port: 3101
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
