{{- if eq .Values.group "infrastructure" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default

  destination:
    namespace: cert-manager
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  # info:
  #   - name: 'Example:'
  #     value: 'https://example.com'

  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.19.2

      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true

          prometheus:
            enabled: true
            servicemonitor:
              enabled: true

          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              cpu: 80m
              memory: 96Mi

          webhook:
            resources:
              requests:
                cpu: 10m
                memory: 20Mi
              limits:
                cpu: 50m
                memory: 50Mi

          cainjector:
            resources:
              requests:
                cpu: 10m
                memory: 40Mi
              limits:
                cpu: 80m
                memory: 96Mi

          startupapicheck:
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 32Mi

    - path: manifests/infrastructure/manifests/cert-manager/
      repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
{{- end }}
