{{- if eq .Values.group "infrastructure" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default

  destination:
    namespace: longhorn
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.12.1

      helm:
        releaseName: longhorn
        valuesObject:
          defaultSettings:
            concurrentReplicaRebuildPerNodeLimit: 1

          longhornUI:
            replicas: 1

          longhornManager:
            resources:
              requests:
                cpu: 250m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi

          persistence:
            defaultClassReplicaCount: 2
            defaultDataLocality: "best-effort"

          preUpgradeChecker:
            jobEnabled: false

          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.cluster.rebelinblue.com
            tls: true
            tlsSecret: longhorn-tls
            path: /
            pathType: ImplementationSpecific
            annotations:
              forecastle.stakater.com/expose: "true"
              forecastle.stakater.com/icon: https://longhorn.io/img/logos/longhorn-icon-white.png
              forecastle.stakater.com/appName: Longhorn
              forecastle.stakater.com/group: Infrastructure
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: {{ include "cluster-apps.certManagerIssuer" (dict "appName" "longhorn" "root" $) }}
              traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
{{- end }}
