{{- if eq .Values.group "infrastructure" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  project: default

  destination:
    namespace: kube-system
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    chart: sealed-secrets
    repoURL: https://bitnami.github.io/sealed-secrets
    targetRevision: 2.18.6

    helm:
      releaseName: sealed-secrets-controller

      valuesObject:
        ingress:
          enabled: false

        # FIXME: Resources

        metrics:
          serviceMonitor:
            enabled: true
          dashboards:
            create: false
{{- end }}
