{{- if and (eq .Values.group "infrastructure") (eq (include "cluster-apps.enabled" (dict "appName" "traefik-forward-auth" "root" $)) "true") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-forward-auth
  namespace: argocd
spec:
  project: default

  destination:
    namespace: traefik
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  source:
    path: manifests/infrastructure/manifests/traefik-forward-auth/
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
{{- end }}
