apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  name: Blackbox Exporter
  group: Monitoring
  icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/prometheus.png
  networkRestricted: true
  properties:
    Version: 0.16.0
  urlFrom:
    ingressRef:
      name: blackbox-exporter
