apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: linkerd
  namespace: linkerd-viz
spec:
  name: Linkerd
  group: Infrastructure
  icon: https://avatars.githubusercontent.com/u/25301026?s=200&v=4
  networkRestricted: true
  properties:
    Version: 2.11.2
  urlFrom:
    ingressRef:
      name: linkerd
