apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: apps
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: forecastle
  interval: 5m
  chart:
    spec:
      chart: ./deployments/kubernetes/chart/forecastle
      sourceRef:
        kind: GitRepository
        name: forecastle
        namespace: flux-system
      version: v1.0.80
  values:
    nameOverride: forecastle

    forecastle:
      createCustomResource: true

      labels: {}

      namespace: apps

      image:
        name: stakater/forecastle
        tag: v1.0.80

      deployment:
        replicas: 1

      config:
        customApps: {}
        headerBackground: null
        headerForeground: null
        instanceName: null
        crdEnabled: true
        namespaceSelector:
          matchNames:
            - logging
            - monitoring
            - kubernetes-dashboard
            - apps
            - infra
            - kube-system
            - vault
            - data
            - linkerd-viz
        title: Launch Pad

      ingress:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-staging
        className: traefik
        hosts:
        - host: launchpad.cluster.rebelinblue.com
          paths:
          - path: /
            pathType: ImplementationSpecific
        tls:
        - hosts:
          - launchpad.cluster.rebelinblue.com
          secretName: forecastle-tls
