apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: event-exporter
  namespace: monitoring
spec:
  releaseName: event-exporter
  interval: 5m

  chart:
    spec:
      chart: kubernetes-event-exporter
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    config:
      logFormat: "json"
      logLevel: "warn"

    metrics:
      enabled: true

      serviceMonitor:
        enabled: true

      prometheusRule:
        enabled: true
