apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    kubernetes.io/description: Prometheus monitoring and alerting
  labels:
    pod-security.kubernetes.io/enforce: privileged
