---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    NOTIFY_URL: AgBkrQcXrHjBtrnWj2th4o7Cuaxia4Sz4/GvanqAViU29ngqNWjZ3UYXPSWE5xo5AKLO4cAzL8VUuXhgO5Lu/duExDnGrCiGNU7fq+HdoVMWEa8vZxIYgBjSTsHtTtkus9SDSlRgFvnAZmKs87RD0Ysr2hsT7MXbadDf62u4xo3EAkB/LRGFW2fNtpbR3bUj728/wrCXYGwgoRUV7mM6sm0uFBcXauPZwRXqO6NrQYlIh+kbZLl+SkNBCXzSZXKttBAlmNgT6hFJ+8T2NTrA8nt6LZtX2pHJhmssVzSLzPnu7ykQtTfW1bgODPZjy6+KWLQmxFQ64zBloRmf9oaPrzAxWyNM1oBCUh2RkBjbpTNgt8e2mCXe/OX1r2Dnttn3JQFVuVREauI6Hjd9V2kYMUJd2OzzQID7rh9iNF+cmezybEU8GTLMqAPRisWHgZ+MjQBDJnHQiegjSMjrmYQ9lh0eor4QsTTLrENGaUIdmvtmvvX445qqnSmwSUMmV7dNUKgfClan6Gls2EmmJ/bTJ5E7HXSq/pYJXgLTnbpywVfdidkxdULNUBgPF/CjxCBsINE3OTElHyJ+XHQrGKwocSv+uzrq2aTj2KUKEX7NQNFn5sfPHe+PusnGX+VDAl2SB+FZZ+9arqR39wA49/367cIkT0VTJkFDN4+j1av0H9kOzJTy/t3jDYYKCzPPRwzB1owtLDzeTNs0lJnNOj00dmFgPM6m1w5ULtLnYkz6thJ/nC/6URf9AjA0CNfIkhTGZqwo3HoL5RIjNcdUxcFUPBwlhK0flSIJ/3sxSsbsJoi4
  template:
    metadata:
      name: kured
      namespace: kube-system
