---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    NOTIFY_URL: AgAUTytH5I6Gt3TDd5j+O96eN3+JMvHuIsxUIzErTE0206Stbf1Q+uDDt5FXvVg0gQRWqov7zOail7+MLe7Xf5pE1SiqLM0VsF/qxe8qIwHoeV7Qk5+RH4uQHw6q1qxdJQFc5oOWERhThuYnhyt1qvmTC5x2Z2JEPzKNBDIsiQ+1nOTE6QKt+f+4K0RHZboq1ZBr3R/dU0w4vmfbo98UBH8ntv/nODpaKyn+Wh5LGZTavHNSSzUJokC3OIj/HANjR+JQQtFuNhtuva7078UbAn8UFBxSfx9FwSXX5Yl5vjuD/WV1scbXmMZAJMzu/tjTd3OpqHOzjjsX+YEclGNk67ZhEUcWBS1q6DB/xebiAdTSC+D2V2LhoChCDpTLvfY7y5BPvhc127z3eP4donIrQxW1KoMksWdRJy/CduNvp/+TEHZg3+pCa1lRXsSEzOaYO8aUi1PU3Pt/PDMJlwYn5TcNci7u2talMNoI6JW8zFTJRVKmBUerBZbSOmlXT9XfjA2I3rOhWxrxc95x1izf7RYgcCvYng7DmNrLQa1McgHAPkgLJKjb/iha+UdDa35L1h+sZtjrH+Hal3N8Cz1FC1QE8wZ2jOweNtVVhf0klwO/ncdvNCsIaC39MA8MeA5GzBAeD64xaJ1be2qdpqPF5c+NdV9NVr22UthXPLuFGCLLokUXssGfqBa8w3II1t72ygtlbzW+sewQj2eicAXN7eddJPo+m0VQNYqU0NGlh+q8uUnPPOmZlcPSxRFyVJ5tCHubq0nLK8+pezONTXkYZSa991bY5CL5swb9IWCoWM8L
  template:
    metadata:
      name: kured
      namespace: kube-system
