---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    NOTIFY_URL: AgB67RGjADwaCYV7OdqYgYbyPO4U1RPo+xp0A0y3IX3qGaehPgSStoAKRbLGizLzlJjPvyNp7422KKdyrC318YOruoLpZZKGwWXQUllcSUXI1BsBkt7xhrv/crClZW6tGbymNUxFm44EBZssxVkGhx6eVDC2/BImPU+V8CizLhKnbz0yK87ekVgnCwuG41WUgdM4oJXbOZUwczXK4ehdp1V5xDX9h+OtlfOh5tnGyJBtLtymxIvA01fFU2yEBaQgxR13A2XVV1O60nvjkctAUff6ArKgSfzXWBIN+7KrhGvw6tF+swlrpPRjySrOBQwcNq8vEeYTgbfKuvnKbmd0PsJgDFuawfXnUDkgbaGC1msG4KC1BHwZW82Pq/wupJp8oXUaxijEelraKKLnkxNaxJMVJhjaLpId/NVF2Zu06EIbN/8n0aE2jsrIZVy8KIWA7MRxyEIjM01ypmCU1Lsbm6+cX6qpchnnME5u+Wf/2U4s2QRTEeD6x0JLgH/1eU5g6SuFhcnvSCkno74rnhner2+24qbwNnhPJcsl6Xd3goX3w/fycmGF+3egYvQ7NFWc0+gzvkBtfuZVv+nzQhP36bZ2BR6boxQg/AZ+6Gc5FfNmJtOpzkRFLtrmFOnAaju1uS/IMzj83zQE7MAJoSbV+rgCZ2y91W538dvEvRTJA9GboQ5egoCABZFVxFCZy19R84ns4VRf+lVHWpBosXiQO7PBvmyT4GYx+76YzCzH2QF8RUw9srrftmlOgbQ0q5zQ87pSHKX5dCU99PgYa2HH/IaXAbNmzS2zDQs+l+464GNL
  template:
    metadata:
      name: kured
      namespace: kube-system
