---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    NOTIFY_URL: AgCLmYq4lhPztsqARcJBc2OEw9DkVzA/HYX39lkM6Jj6gbrQgFMwQ1snBqXMzARv2pwUOQtzAgb/83LB+nhMCoQTdXjXouGjKGqOdVoihNSSjB40vmqFNgPAnFptHfnpoolmr9y9d0P0Iph7iut+twyGOoKUpv9Lfj1/5XkZIEoBVcAKLoVN/kVeKdSF3p3O8qSqL5jdEL9uKmsNKVKRZoVASYdY3xqYzbj3gf+sfvFuqKHmdyhfYOONq2NzhvP14fe2TmbPNHK2KSzMkZP+aoyR11jlJHGTxRWlVUHQJwvmdJS8V30VmwQD2ix42DoBydHTcSq+ZqGlIdNOnCocJEVCx24kXxLyPmJrIlYn3Bdvs/h3EksZ8N+RpFwL3L8XNhBQ1FwywifUFTUGqbWLYG8R7qSNHwdoivD9KmczKGLiwMqh2BMYl9eXdvNqjKtYKsDBXnaPyW7kv03BtRonGV6F0QHiN64j25dUcMC1vpAInabwm2z8ugDCYiVa0owfZfUwJWANkHy5JU9KV3BE2mAPXArNnvvJzig1GMERiksG5ad8GM0VJF9LFS96u+EzJiesfoe6N0zsad0uI6+5RwNPOcdIf4yJt81kJixXbQqopov6vjuhBU53d5OiUH6hhnG7/pgKzh9xfpQcydTKeMCwdPidjv1FT5DSAmhEh9K6R4eH0YNSc9qkebrjphZMpjdFpETWSetarR/pBzBOCWQ8rgGHzb0APcbRp4EqmuKqgspEpa18NwMv4j+59rnnn6DZqrJnKFCOweN+CLqpGGFsrf5csbHU8Y2VQy0pzdpb
  template:
    metadata:
      name: kured
      namespace: kube-system
