---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    NOTIFY_URL: AgAN+lDMl+Gtk9QFXj+F22WctqCV+hWBPPWLj8z6EouN96Nx9jcq3bsFcHiFKrGIEQgcq1ZwTTUTvQh52pIC2Spe53fmWYmfX1jLdDnTsibR28WEMbgjP50SZbKEjCjB1OpJkArL1fo26ruiAaDGb4cMJipMg7YFOvrdEz2exAiSj8eF4IlIA0X5gnob2JSxu4jVXxnCj5xH8Xzh8T+B0Wo8JwTwljn1XH2B9HFES9mxaKZGw5vmeRttDv+JmlDKRBu5bL60prw2isvYd0T7uMrWRyvktWxDlhFqJyCr335OrfIXLSzBqOqUbjKKvFU2PczGtDSnGA8w671mEVgIQB2NmFtMwnFVX+bCxLZNFoqoW1+NERucYkW/uI9S7awDvk/W9hqgYUcA4dyKYbX63VjYbXV919EIuZq1ebva5TDnZGTWuhcva1WgdkwcOKd41q0fRe/fTBQ8BOqDy30h1J9k/WqbfKszINcRA7Xr8G3z3SUdHM+e2+Q8ZhFspUfsU8GVuOjgiUY4twP7OpfBzf/5s8FhKuJCubKnUWCWUSsyg95+odmlhdEwGCdMi+uyF0ThtQ0Z/kzJ49lqWkMI5plDRDpT/Mk5d089eFQS/WkrZ+EXZ0GIXP3L1aRL78zbvo7tuVd6mYA8h9hA54sdcZKiIYmsLaOBMVDzMAqURW4mN6s7ZP//tGBmfeC8KEWvzxSkm+w3T17DqB/Ih2SO6fmruYOwLEa/D8mZBkwz7IrrYmuiwODvCpaxi49nzrtBdzhe6T2nBv7vnABl7RWVq6uqMunf3rt1sl3sXd2FsAyO
  template:
    metadata:
      name: kured
      namespace: kube-system
