apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: loki
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      version: 0.29.0
  values:
    fullnameOverride: loki

    image:
      repository: grafana/loki
      tag: 1.5.0-arm
      pullPolicy: Always

    persistence:
      enabled: true
      storageClassName: nfs-hdd

    serviceMonitor:
      enabled: false # true
