apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: loki
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 2.8.1
  values:
    fullnameOverride: loki

    ingress:
      enabled: false

    image:
      repository: grafana/loki
      tag: 2.4.1-arm
      pullPolicy: Always

    persistence:
      enabled: true
      storageClassName: nfs-hdd

    serviceMonitor:
      enabled: true
