apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: promtail
  interval: 5m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 3.9.1
  values:
    fullnameOverride: promtail

    image:
      repository: grafana/promtail
      tag: 1.5.0-arm
      pullPolicy: Always

    pipelineStages:
      - cri: {}

    loki:
      serviceName: loki
      servicePort: 3100
      serviceScheme: http

    serviceMonitor:
      enabled: false #true

    volumes:
      - name: containers
        hostPath:
          path: /var/log/containers
      - name: pods
        hostPath:
          path: /var/log/pods

    volumeMounts:
      - name: containers
        mountPath: /var/log/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods
        readOnly: true

    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
