apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: infra
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: registry
  interval: 5m
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      version: 2.1.0
  values:
    nameOverride: registry

    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      size: 10Gi
      storageClass: local-path

    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane

    nodeSelector:
      beta.kubernetes.io/arch: arm64
      node-role.kubernetes.io/control-plane: "true"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      className: traefik
      path: /
      hosts:
        - registry.cluster.rebelinblue.com
      tls:
        - hosts:
          - registry.cluster.rebelinblue.com
          secretName: registry-tls

    secrets:
      htpasswd: "stephen:$2y$05$.aUqmn4GOa6H4A3kAIOeLu0XfCGQk1Nhfev9XH2TO0PKlRUpkoQKy"
