# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: communication-slack
#   namespace: monitoring
# type: Opaque
# stringData:
#   comm_config.yaml: |  
#     communications:
#       slack:  
#         enabled: true
#         channel: k8s-alerts
#         token: xoxb-45148463796-4904352324946-GhBSl992dz4e3rHgnOcPSOcL
#         notiftype: short
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  releaseName: botkube
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v0.12.4
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: botkube
    image:
      registry: docker.io
      repository: raspbernetes/botkube
      tag: v0.12.4
      pullPolicy: Always
    config:
      settings:
        upgradeNotifier: false
        clustername: rpi
        kubectl:
          enabled: true
          commands:
            verbs: ["api-resources", "api-versions", "describe", "diff", "explain", "get", "logs", "top", "auth"]
            resources: ["deployments", "pods", "namespaces", "daemonsets", "statefulsets", "storageclasses", "nodes"]
      resources:
        - name: v1/pods
          namespaces:
            include:
              - all
            ignore:
              - linkerd
          events:
            - create
            - delete
            - error
        - name: v1/services
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.availableReplicas
        - name: apps/v1/statefulsets
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.readyReplicas
        - name: networking.k8s.io/v1/ingresses
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/configmaps
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: apps/v1/daemonsets
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.numberReady
        - name: batch/v1/jobs
          namespaces:
            ignore:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.conditions[*].type
        - name: rbac.authorization.k8s.io/v1/roles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/rolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterrolebindings
          namespaces:
            include:
              - al
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterroles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: helm.toolkit.fluxcd.io/v2beta1/helmreleases
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: helm.toolkit.fluxcd.io/v1beta1/helmrepositories
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: helm.toolkit.fluxcd.io/v1/gitrepositories
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: traefik.containo.us/v1alpha1/middlewares
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: monitoring.coreos.com/v1/servicemonitors
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: monitoring.coreos.com/v1/prometheusrules
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: cert-manager.io/v1/certificates
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
        - name: velero.io/v1/backups
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - status.phase
    serviceMonitor:
      enabled: true
    communications:
      existingSecretName: communication-slack