---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: infra
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      annotations:
        SECRET_CLIENT_ID: /apps/infra/traefik-forward-auth/CLIENT_ID
        SECRET_CLIENT_SECRET: /apps/infra/traefik-forward-auth/CLIENT_SECRET
        SECRET_SECRET: /apps/infra/traefik-forward-auth/SECRET
      labels:
        app: traefik-forward-auth
    spec:
      initContainers:
        - name: init
          image: rebelinblue/vault-consumer:0.0.3
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  key: role_id
                  name: traefik-forward-auth-approle
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  key: secret_id
                  name: traefik-forward-auth-approle
          volumeMounts:
            - mountPath: /env
              name: env
            - mountPath: /tmpfs
              name: podinfo
      containers:
        - image: rebelinblue/traefik-forward-auth:2.0.0-rc2
          name: traefik-forward-auth
          command:
            - sh
            - -c
          args:
            - source /env/secrets; /traefik-forward-auth -log-level=info
          ports:
            - containerPort: 4181
              protocol: TCP
          env:
            - name: OIDC_ISSUER
              value: https://accounts.google.com
            - name: AUTH_HOST
              value: auth.cluster.rebelinblue.com
            - name: COOKIE_DOMAINS
              value: cluster.rebelinblue.com
            - name: WHITELIST
              value: stephen.ball@gmail.com,stephen.ball@lendinvest.com
            - name: COOKIE_SECURE
              value: "false"
          livenessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /env
              name: env
      volumes:
        - name: env
          emptyDir: {}
        - name: podinfo
          downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-forward-auth
  namespace: infra
spec:
  selector:
    app: traefik-forward-auth
  ports:
    - port: 80
      targetPort: 4181
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-forward-auth
  namespace: infra
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.middlewares: infra-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: auth.cluster.rebelinblue.com
      http:
       paths:
          - backend:
              service:
                name: traefik-forward-auth
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - auth.cluster.rebelinblue.com
      secretName: auth-tls
