apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default

  destination:
    namespace: monitoring
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - kind: "Secret"
        jsonPointers:
          - /data/admin-password
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/metadata/annotations/checksum~1secret
    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: 0.91.2

      helm:
        releaseName: vm

        valuesObject:
          argocdReleaseOverride: victoria-metrics

          # VictoriaMetrics
          vmsingle:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - metrics.cluster.rebelinblue.com
              path: /
              tls:
                - secretName: metrics-ingress-tls
                  hosts:
                    - metrics.cluster.rebelinblue.com

          # VictoriaTraces
          vtsingle:
            enabled: false
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - traces.cluster.rebelinblue.com
              path: /
              tls:
                - secretName: traces-ingress-tls
                  hosts:
                    - traces.cluster.rebelinblue.com
            spec:
              retentionPeriod: 3d
              storage:
                resources:
                  requests:
                    storage: 10Gi

          # VictoriaLogs Collector
          vlagent:
            enabled: true
            spec:
              k8sCollector:
                enabled: true

          # VictoriaLogs Storage
          vlsingle:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - logs.cluster.rebelinblue.com
              path: /
              tls:
                - secretName: logs-ingress-tls
                  hosts:
                    - logs.cluster.rebelinblue.com
            spec:
              resources:
                requests:
                  memory: 64Mi
                  cpu: 250m
                limits:
                  memory: 128Mi
                  cpu: 500m
              retentionPeriod: 30d
              storage:
                resources:
                  requests:
                    storage: 10Gi

          alertmanager:
            enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              hosts:
                - alertmanager.cluster.rebelinblue.com
              path: /
              tls:
                - secretName: alertmanager-ingress-tls
                  hosts:
                    - alertmanager.cluster.rebelinblue.com

          grafana:
            enabled: true
            ingress:
              enabled: true
              annotations:
                kubernetes.io/tls-acme: "true"
                cert-manager.io/cluster-issuer: letsencrypt-staging
                traefik.ingress.kubernetes.io/router.middlewares: ingress-forward-auth@kubernetescrd
              path: /
              pathType: Prefix
              hosts:
                - grafana.cluster.rebelinblue.com
              tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.cluster.rebelinblue.com

            grafana.ini:
              users:
                auto_assign_org: true
                auto_assign_org_role: Admin
              auth:
                disable_login_form: true
                disable_signout_menu: true
              auth.anonymous:
                enabled: true
                org_role: Admin
              auth.basic:
                enabled: false
              auth.proxy:
                enabled: false
                header_name: X-Forwarded-User
                header_property: email
                auto_sign_up: true
              alerting:
                enabled: false
              unified_alerting:
                enabled: false
              analytics:
                check_for_updates: false

            plugins:
              - victoriametrics-metrics-datasource
              - victoriametrics-logs-datasource

          defaultDashboards:
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true
