---
- name: Ensure Kubernetes cluster entries are present in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].cluster_ip }}\\s+{{ item }}"
    line: "{{ hostvars[item].cluster_ip }}\t{{ item }}"
    state: present
  loop: "{{ groups['all'] }}"
