---
- name: Control Plane Configuration
  hosts: controlplane
  gather_facts: false

  tasks:
    - name: Check if K3s binary exists
      register: k3s_bin
      ansible.builtin.stat:
        path: /usr/local/bin/k3s

    - name: Download K3s install script
      when: not k3s_bin.stat.exists
      become: true
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0755"

    - name: Install K3s on Control Plane
      become: true
      ansible.builtin.command: /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_EXEC: "--tls-san cluster.lan --disable metrics-server --disable traefik --disable local-storage --disable servicelb"

    - name: Read the node token
      become: true
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_file

    - name: Set node token as a fact
      ansible.builtin.set_fact:
        k3s_node_token: "{{ node_token_file.content | b64decode | trim }}"

- name: Install K3s in worker nodes
  hosts: workers
  gather_facts: false
  serial: 1
  tasks:
    - name: Check if K3s binary exists
      register: k3s_bin
      ansible.builtin.stat:
        path: /usr/local/bin/k3s

    - name: Download K3s install script
      when: not k3s_bin.stat.exists
      become: true
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0755"

    - name: Install K3s agents
      become: true
      ansible.builtin.command: /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        K3S_URL: "https://10.0.0.1:6443"
        K3S_TOKEN: "{{ hostvars[groups['controlplane'][0]].k3s_node_token }}"
