---
- name: Install K3s on master node
  hosts: controlplane
  gather_facts: false

  tasks:
    - name: Check if K3s binary exists
      register: k3s_bin
      ansible.builtin.stat:
        path: /usr/local/bin/k3s

    - name: Download K3s install script
      when: not k3s_bin.stat.exists
      become: true
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0755"

    - name: Install K3s server
      become: true
      ansible.builtin.command: /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_EXEC: "--node-taint node-role.kubernetes.io/control-plane:NoSchedule --tls-san cluster.lan --disable metrics-server --disable traefik --disable servicelb --disable local-storage"

    - name: Read kubeconfig
      become: true
      register: k3s_config_raw
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml

    - name: Create temp file for kubeconfig
      delegate_to: localhost
      register: k3s_config_tempfile
      ansible.builtin.tempfile:
        state: file
        suffix: k3s_config

    - name: Write updated kubeconfig to temp file
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "{{ k3s_config_tempfile.path }}"
        content: "{{ k3s_config_raw.content | b64decode | regex_replace('https://127\\.0\\.0\\.1', 'https://cluster.lan') | regex_replace('default', 'pi') }}"
        mode: "0600"

    - name: Back up local kubeconfig
      delegate_to: localhost
      ansible.builtin.copy:
        src: ~/.kube/config
        dest: ~/.kube/config.bak
        remote_src: true
        mode: "0600"
      ignore_errors: true

    - name: Ensure local kubeconfig exists
      delegate_to: localhost
      ansible.builtin.file:
        path: ~/.kube/config
        state: touch
        mode: "0600"
        access_time: preserve
        modification_time: preserve

    - name: Merge kubeconfig into local kube config
      delegate_to: localhost
      ansible.builtin.command: kubecm add -f {{ k3s_config_tempfile.path }} --create --cover

    - name: Delete temp kubeconfig file
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ k3s_config_tempfile.path }}"
        state: absent

    - name: Read the node token
      become: true
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_file

    - name: Set node token as a fact
      ansible.builtin.set_fact:
        k3s_node_token: "{{ node_token_file.content | b64decode | trim }}"

- name: Install K3s on worker nodes
  hosts: workers
  gather_facts: false
  serial: 1
  tasks:
    - name: Check if K3s binary exists
      register: k3s_bin
      ansible.builtin.stat:
        path: /usr/local/bin/k3s

    - name: Download K3s install script
      when: not k3s_bin.stat.exists
      become: true
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0755"

    - name: Install K3s agents
      become: true
      ansible.builtin.command: /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        K3S_URL: "https://{{ hostvars[groups['controlplane'][0]].cluster_ip }}:6443"
        K3S_TOKEN: "{{ hostvars[groups['controlplane'][0]].k3s_node_token }}"

- name: Bootstrap cluster
  hosts: controlplane
  gather_facts: false

  tasks:
    - name: Copy ArgoCD manifest
      become: true
      ansible.builtin.copy:
        src: files/argocd.yaml
        dest: /var/lib/rancher/k3s/server/manifests/argocd.yaml
        mode: "0600"

    - name: Copy CRDs manifest
      become: true
      ansible.builtin.copy:
        src: files/crds.yaml
        dest: /var/lib/rancher/k3s/server/manifests/crds.yaml
        mode: "0600"

    - name: Wait for ArgoCD initial admin password
      become: true
      register: argocd_admin_secret
      changed_when: false
      until: argocd_admin_secret.rc == 0
      retries: 30
      delay: 10
      ansible.builtin.command: >-
        kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath={.data.password}

    - name: Print ArgoCD initial admin password
      ansible.builtin.debug:
        msg: "ArgoCD initial admin password: {{ argocd_admin_secret.stdout | b64decode }}"
