---
- name: Control Plane Configuration
  hosts: controlplane
  gather_facts: false

  roles:
    - role: cleanup
    - role: config
    - role: packages
      vars:
        packages_additional:
          - isc-dhcp-server
          - iptables
    - role: master
    - role: hosts
    - role: cgroups
    - role: shell
    # TODO: Not sure topgrade is necessary
    - role: topgrade
    - role: starship
