---
- name: Reboot cluster worker nodes
  hosts: workers
  become: true
  gather_facts: false

  roles:
    - reboot

- name: Reboot cluster control plane nodes
  hosts: controlplane
  become: true
  gather_facts: false

  roles:
    - reboot
