---
- name: Uninstall K3s from worker nodes
  hosts: workers
  gather_facts: false
  become: true
  tasks:
    - name: Run K3s agent uninstall script
      ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
      args:
        removes: /var/lib/rancher/k3s

    - name: Remove node from cluster
      delegate_to: "{{ groups['controlplane'][0] }}"
      ansible.builtin.command: kubectl delete node {{ inventory_hostname }}
      failed_when: false
      changed_when: false

- name: Uninstall K3s from control plane nodes
  hosts: controlplane
  gather_facts: false
  become: true
  tasks:
    - name: Run K3s uninstall script
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      args:
        removes: /var/lib/rancher/k3s

- name: Clean up residual files
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Remove directories related to container runtimes and K3s
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker
        - /var/lib/containerd
        - /var/lib/cni
        - /var/log/containers
        - /var/log/pods
        - /var/lib/rancher
        - /etc/rancher
        - /etc/cni
        - /etc/containerd
        - /etc/docker
        - /opt/local-path-provisioner
        - /var/lib/longhorn

- name: Reboot cluster worker nodes
  hosts: workers
  become: true
  gather_facts: false
  roles:
    - reboot

- name: Reboot cluster control plane nodes
  hosts: controlplane
  become: true
  gather_facts: false
  roles:
    - reboot

- name: Clean up local kubeconfig
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Remove pi context from local kube config
      ansible.builtin.command: "{{ item }}"
      loop:
        - kubectl config unset current-context
        - kubectl config delete-cluster pi
        - kubectl config delete-user pi
        - kubectl config delete-context pi
      failed_when: false

