---
- name: Workers Configuration
  hosts: workers
  gather_facts: false

  roles:
    - role: cleanup
    - role: config
    - role: packages
      vars:
        packages_additional:
          - rfkill
    - role: hosts
    - role: cgroups
    - role: shell
    - role: topgrade
    - role: starship
