apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd2
  namespace: linkerd
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: loki
  interval: 5m
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: 2.11.2
  values:
    fullnameOverride: linkerd2

    installNamespace: false

    identity:
      issuer:
        scheme: kubernetes.io/tls