apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: grafana
  namespace: monitoring
spec:
  name: Grafana
  group: Monitoring
  icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/grafana.png
  networkRestricted: true
  properties:
    Version: 6.4.4
  urlFrom:
    ingressRef:
      name: grafana
