apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: prometheus
  namespace: monitoring
spec:
  name: Prometheus
  group: Monitoring
  icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/prometheus.png
  networkRestricted: true
  properties:
    Version: 2.14.0
  urlFrom:
    ingressRef:
      name: prometheus-k8s