apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: rabbitmq
  namespace: data
spec:
  name: RabbitMQ UI
  group: Messaging
  icon: https://avatars0.githubusercontent.com/u/96669?s=200&v=4
  networkRestricted: false
  properties:
    Version: 3.8.34
  urlFrom:
    ingressRef:
      name: rabbitmq-ui
