apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default

  destination:
    namespace: local-path-storage
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  # fixme: convert to helm chart
  source:
    path: manifests/infrastructure/manifests/local-path-provisioner/
    repoURL: https://github.com/REBELinBLUE/k3s-rpi-cluster
    targetRevision: main
