# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: stable
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   url: https://charts.helm.sh/stable
# ---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: infracloudio-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://infracloudio.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://vmware-tanzu.github.io/helm-charts
---
