additionalArguments:
  - "--providers.kubernetesingress.ingressendpoint.ip=192.168.115.193"

providers:
  kubernetesCRD:
    enabled: true

  kubernetesIngress:
    enabled: true
    # Does not work as using NodePort service rather than LoadBalancer
    #publishedService:
    #  enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  type: NodePort
  externalIPs:
    - 192.168.115.193

logs:
  general:
    level: DEBUG
  access:
    enabled: true

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

requests:
  cpu: 25m
  memory: 128Mi
limits:
  cpu: 200m
  meomry: 384Mi

ports:
  traefik:
    expose: true
    port: 9000
  web:
    hostPort: 80
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
    hostPort: 443

pilot:
  enabled: false
  dashboard: false

ingressRoute:
  dashboard:
    enabled: true

metrics:
  prometheus:
    enabled: true
