global:
  rbac:
    create: true

    ## Create ClusterRoles that extend the existing view, edit and admin ClusterRoles to interact with prometheus-operator CRDs
    ## Ref: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
    createAggregateClusterRoles: true
    # Use PodSecurityPolicies
    pspEnabled: false
    pspAnnotations: { }


## Component scraping the kube-apiserver
##
kubeApiServer:
  enabled: true

## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: true

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: true

## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    darwin:
      enabled: false

prometheus-node-exporter:
  priorityClassName: system-node-critical

## Component scraping kube proxy
##
kubeProxy:
  enabled: true

## Component scraping the kube-controller-manager
kubeControllerManager:
  enabled: true

## Component scraping etcd
##
kubeEtcd:
  enabled: false # not relevant to K3S

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: true

## Component scraping kube state metrics
##
kubeStateMetrics:
  enabled: true

## Thanos ruler
##
thanosRuler:
  enabled: false
