## Operator for managing Prometheus
prometheusOperator:
  enabled: true

  clusterDomain: "cluster.local"

  tls:
    tlsMinVersion: VersionTLS13

  hostNetwork: false

  service:
    type: ClusterIP

  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi

  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  prometheusConfigReloader:
    # resource config for prometheusConfigReloader
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi
