apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: ingress
spec:
  forwardAuth:
    address: http://traefik-forward-auth.ingress.svc
    authResponseHeaders:
      - X-Forwarded-User


